-- ============================================================================
-- 自动生成 (工具_生成22级用户.py) — 请勿手工修改
-- ============================================================================
USE online_exam_system;
SET FOREIGN_KEY_CHECKS = 0;
START TRANSACTION;


-- ============================================================
-- 区段 A: 公共教研室教师 (15 位, id 700-714)
-- 复用 24 级公共教师: 高数A/英语/日语/线代/概率 不在此新建
-- ============================================================
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (700, 'zhangwenge', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '张文革', 'zhangwenge@tpxy.usts.edu.cn', '13562851956', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (701, 'lihong2022', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '李红', 'lihong2022@tpxy.usts.edu.cn', '13150188411', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (702, 'chenjianguo', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '陈建国', 'chenjianguo@tpxy.usts.edu.cn', '13465652291', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (703, 'liuzhongcheng', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '刘忠诚', 'liuzhongcheng@tpxy.usts.edu.cn', '13079574928', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (704, 'wanglijun', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '王立军', 'wanglijun@tpxy.usts.edu.cn', '13692159674', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (705, 'zhaoweiguo', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '赵卫国', 'zhaoweiguo@tpxy.usts.edu.cn', '13564421372', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (706, 'huangxinyi2022', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '黄欣怡', 'huangxinyi2022@tpxy.usts.edu.cn', '13701050704', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (707, 'chenyajing', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '陈雅静', 'chenyajing@tpxy.usts.edu.cn', '13394918942', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (708, 'zhangmingjie', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '张铭杰', 'zhangmingjie@tpxy.usts.edu.cn', '13041142184', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (709, 'liuwenbo', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '刘文博', 'liuwenbo@tpxy.usts.edu.cn', '13767108872', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (710, 'qiansiyuan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '钱思源', 'qiansiyuan@tpxy.usts.edu.cn', '13407870113', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (711, 'linxueying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '林学英', 'linxueying@tpxy.usts.edu.cn', '13487892259', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (712, 'wuhaitao', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '吴海涛', 'wuhaitao@tpxy.usts.edu.cn', '13186058167', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (713, 'zhengwenqing', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '郑文清', 'zhengwenqing@tpxy.usts.edu.cn', '13220636475', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (714, 'shenyaqin', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '沈雅琴', 'shenyaqin@tpxy.usts.edu.cn', '13405777312', 1, 2, 1, NOW());

-- ============================================================
-- 区段 B: 专业课教师 (100 位, id 715-814)
-- 25 专业 × 4 位, 仅教本专业核心+选修课
-- ============================================================
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (715, 'jinxiying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '金希颖', 'jinxiying@tpxy.usts.edu.cn', '13643149473', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (716, 'kangxin', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '康欣', 'kangxin@tpxy.usts.edu.cn', '13600757674', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (717, 'duxiaoqiang', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '杜晓强', 'duxiaoqiang@tpxy.usts.edu.cn', '13795384058', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (718, 'zhongxinlei', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '钟欣蕾', 'zhongxinlei@tpxy.usts.edu.cn', '13931347818', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (719, 'zouyanjun', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '邹艳军', 'zouyanjun@tpxy.usts.edu.cn', '13945674421', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (720, 'xuehaiyu', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '薛海宇', 'xuehaiyu@tpxy.usts.edu.cn', '13905345047', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (721, 'dengzhijie', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '邓志杰', 'dengzhijie@tpxy.usts.edu.cn', '13700737423', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (722, 'xiaomengfeng', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '萧梦峰', 'xiaomengfeng@tpxy.usts.edu.cn', '13801716784', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (723, 'gaoshirui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '高诗睿', 'gaoshirui@tpxy.usts.edu.cn', '13494919272', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (724, 'tianwenlin', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '田文琳', 'tianwenlin@tpxy.usts.edu.cn', '13713990640', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (725, 'luyanqiang', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '卢艳强', 'luyanqiang@tpxy.usts.edu.cn', '13508746580', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (726, 'zhongying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '钟颖', 'zhongying@tpxy.usts.edu.cn', '13787577881', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (727, 'liuxiaolin', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '刘晓琳', 'liuxiaolin@tpxy.usts.edu.cn', '13040286426', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (728, 'xiamingrui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '夏明蕊', 'xiamingrui@tpxy.usts.edu.cn', '13113332912', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (729, 'xiemingyu', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '谢明宇', 'xiemingyu@tpxy.usts.edu.cn', '13663680557', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (730, 'panchenrui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '潘辰蕊', 'panchenrui@tpxy.usts.edu.cn', '13395370505', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (731, 'hejiahong', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '何佳红', 'hejiahong@tpxy.usts.edu.cn', '13210657731', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (732, 'zhufeng', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '朱峰', 'zhufeng@tpxy.usts.edu.cn', '13458177187', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (733, 'wuyaming', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '吴雅明', 'wuyaming@tpxy.usts.edu.cn', '13799049438', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (734, 'songjunhao', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '宋俊昊', 'songjunhao@tpxy.usts.edu.cn', '13101982197', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (735, 'heruoying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '何若英', 'heruoying@tpxy.usts.edu.cn', '13295549271', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (736, 'xueyajuan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '薛亚娟', 'xueyajuan@tpxy.usts.edu.cn', '13655074115', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (737, 'sumingyi', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '苏明怡', 'sumingyi@tpxy.usts.edu.cn', '13048549176', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (738, 'yaomengrui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '姚梦睿', 'yaomengrui@tpxy.usts.edu.cn', '13678952390', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (739, 'yuchentong', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '于辰彤', 'yuchentong@tpxy.usts.edu.cn', '13750068215', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (740, 'dongyongyi', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '董永怡', 'dongyongyi@tpxy.usts.edu.cn', '13690718435', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (741, 'yemeijuan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '叶美娟', 'yemeijuan@tpxy.usts.edu.cn', '13108349380', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (742, 'baifangfeng', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '白芳峰', 'baifangfeng@tpxy.usts.edu.cn', '13437820509', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (743, 'shenfei', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '沈飞', 'shenfei@tpxy.usts.edu.cn', '13669148652', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (744, 'renfangli', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '任芳丽', 'renfangli@tpxy.usts.edu.cn', '13359440322', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (745, 'wangqiang', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '王强', 'wangqiang@tpxy.usts.edu.cn', '13917276801', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (746, 'fuyuchen', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '傅语辰', 'fuyuchen@tpxy.usts.edu.cn', '13312210984', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (747, 'huangjiaying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '黄佳英', 'huangjiaying@tpxy.usts.edu.cn', '13945696841', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (748, 'luolingyuan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '罗玲远', 'luolingyuan@tpxy.usts.edu.cn', '13596172004', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (749, 'fangruoyi', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '方若怡', 'fangruoyi@tpxy.usts.edu.cn', '13895267290', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (750, 'yangxiying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '杨希英', 'yangxiying@tpxy.usts.edu.cn', '13473851836', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (751, 'yaomeihao', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '姚美昊', 'yaomeihao@tpxy.usts.edu.cn', '13741247647', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (752, 'yaowei', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '姚伟', 'yaowei@tpxy.usts.edu.cn', '13884102014', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (753, 'fangruoying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '方若英', 'fangruoying@tpxy.usts.edu.cn', '13306879399', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (754, 'tangning', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '唐宁', 'tangning@tpxy.usts.edu.cn', '13321588216', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (755, 'liaoxiucheng', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '廖秀诚', 'liaoxiucheng@tpxy.usts.edu.cn', '13503479886', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (756, 'fanyajuan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '范亚娟', 'fanyajuan@tpxy.usts.edu.cn', '13853301729', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (757, 'guoruowen', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '郭若雯', 'guoruowen@tpxy.usts.edu.cn', '13420185395', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (758, 'zhaoqianming', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '赵茜明', 'zhaoqianming@tpxy.usts.edu.cn', '13573627060', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (759, 'zhaozhiwen', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '赵志雯', 'zhaozhiwen@tpxy.usts.edu.cn', '13595683434', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (760, 'xuejie', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '薛洁', 'xuejie@tpxy.usts.edu.cn', '13579234370', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (761, 'shiqing', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '石清', 'shiqing@tpxy.usts.edu.cn', '13050672668', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (762, 'fandan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '范丹', 'fandan@tpxy.usts.edu.cn', '13689509094', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (763, 'linminghua', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '林明华', 'linminghua@tpxy.usts.edu.cn', '13223870011', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (764, 'jiangweiying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '姜伟英', 'jiangweiying@tpxy.usts.edu.cn', '13746813352', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (765, 'zhengjiajie', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '郑佳杰', 'zhengjiajie@tpxy.usts.edu.cn', '13212216010', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (766, 'yuanliqiang', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '袁丽强', 'yuanliqiang@tpxy.usts.edu.cn', '13308443263', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (767, 'hefangying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '何芳英', 'hefangying@tpxy.usts.edu.cn', '13636848035', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (768, 'shenjiajie', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '沈佳杰', 'shenjiajie@tpxy.usts.edu.cn', '13675919876', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (769, 'xielingyi', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '谢玲怡', 'xielingyi@tpxy.usts.edu.cn', '13085763209', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (770, 'jinmengtong', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '金梦彤', 'jinmengtong@tpxy.usts.edu.cn', '13845770875', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (771, 'shijianrui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '史建蕊', 'shijianrui@tpxy.usts.edu.cn', '13198227294', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (772, 'sunruobo', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '孙若博', 'sunruobo@tpxy.usts.edu.cn', '13471428944', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (773, 'jiangzijie', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '江子杰', 'jiangzijie@tpxy.usts.edu.cn', '13374450536', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (774, 'jiangli', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '蒋丽', 'jiangli@tpxy.usts.edu.cn', '13041423245', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (775, 'xiongfeng', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '熊峰', 'xiongfeng@tpxy.usts.edu.cn', '13981076962', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (776, 'weiyaxin', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '魏亚欣', 'weiyaxin@tpxy.usts.edu.cn', '13571594714', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (777, 'chenminglin', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '陈明琳', 'chenminglin@tpxy.usts.edu.cn', '13878919476', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (778, 'fengchunwen', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '冯春雯', 'fengchunwen@tpxy.usts.edu.cn', '13266142083', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (779, 'sujunjie', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '苏俊杰', 'sujunjie@tpxy.usts.edu.cn', '13186620291', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (780, 'tangmenghui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '唐梦辉', 'tangmenghui@tpxy.usts.edu.cn', '13457949878', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (781, 'zhouyuying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '周雨颖', 'zhouyuying@tpxy.usts.edu.cn', '13055538628', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (782, 'shizirui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '史紫蕊', 'shizirui@tpxy.usts.edu.cn', '13452744197', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (783, 'yelei', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '叶磊', 'yelei@tpxy.usts.edu.cn', '13042903056', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (784, 'zoushifeng', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '邹诗峰', 'zoushifeng@tpxy.usts.edu.cn', '13191601199', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (785, 'zhongshichen', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '钟诗辰', 'zhongshichen@tpxy.usts.edu.cn', '13596816330', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (786, 'liuhui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '刘辉', 'liuhui@tpxy.usts.edu.cn', '13865939721', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (787, 'renjiajuan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '任佳娟', 'renjiajuan@tpxy.usts.edu.cn', '13094863593', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (788, 'dongweiqiang', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '董伟强', 'dongweiqiang@tpxy.usts.edu.cn', '13353068360', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (789, 'daijian', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '戴健', 'daijian@tpxy.usts.edu.cn', '13318945602', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (790, 'qinyan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '秦艳', 'qinyan@tpxy.usts.edu.cn', '13897071884', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (791, 'fangyunze', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '方云泽', 'fangyunze@tpxy.usts.edu.cn', '13496779323', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (792, 'qinyong', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '秦勇', 'qinyong@tpxy.usts.edu.cn', '13926940578', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (793, 'jinshixuan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '金诗萱', 'jinshixuan@tpxy.usts.edu.cn', '13929813546', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (794, 'jinliyan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '金丽燕', 'jinliyan@tpxy.usts.edu.cn', '13305912628', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (795, 'wangminghong', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '汪明红', 'wangminghong@tpxy.usts.edu.cn', '13174980081', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (796, 'liwenmei', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '李文梅', 'liwenmei@tpxy.usts.edu.cn', '13399171425', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (797, 'luoying', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '罗颖', 'luoying@tpxy.usts.edu.cn', '13818703954', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (798, 'sunhaihao', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '孙海昊', 'sunhaihao@tpxy.usts.edu.cn', '13881063641', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (799, 'zhubin', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '朱斌', 'zhubin@tpxy.usts.edu.cn', '13819875648', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (800, 'yanchenlei', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '阎辰蕾', 'yanchenlei@tpxy.usts.edu.cn', '13496601266', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (801, 'xujiating', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '许佳婷', 'xujiating@tpxy.usts.edu.cn', '13241320803', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (802, 'cuizihui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '崔子辉', 'cuizihui@tpxy.usts.edu.cn', '13242633835', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (803, 'lishihui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '李诗辉', 'lishihui@tpxy.usts.edu.cn', '13716003127', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (804, 'fanshirui', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '范诗蕊', 'fanshirui@tpxy.usts.edu.cn', '13401892758', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (805, 'caihongcheng', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '蔡宏诚', 'caihongcheng@tpxy.usts.edu.cn', '13634682510', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (806, 'tangna', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '唐娜', 'tangna@tpxy.usts.edu.cn', '13034319117', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (807, 'yanruochen', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '阎若辰', 'yanruochen@tpxy.usts.edu.cn', '13131869886', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (808, 'gaoqianjie', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '高茜杰', 'gaoqianjie@tpxy.usts.edu.cn', '13419227475', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (809, 'chenyubo', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '陈雨波', 'chenyubo@tpxy.usts.edu.cn', '13083216600', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (810, 'jinshijie', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '金诗杰', 'jinshijie@tpxy.usts.edu.cn', '13942828750', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (811, 'xuxuexuan', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '徐雪萱', 'xuxuexuan@tpxy.usts.edu.cn', '13850724504', 2, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (812, 'yanzhifeng', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '阎志峰', 'yanzhifeng@tpxy.usts.edu.cn', '13459704857', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (813, 'shizifang', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '石紫芳', 'shizifang@tpxy.usts.edu.cn', '13035554710', 1, 2, 1, NOW());
INSERT INTO sys_user (id, username, password, real_name, email, phone, gender, role_id, status, create_time) VALUES (814, 'cuihao', '$2a$10$6d9o0ZL1fKx/Zr9AR9CzjuhvPqGFZXPUql/xlzBsmMlaA.4xqRb6u', '崔豪', 'cuihao@tpxy.usts.edu.cn', '13399354014', 2, 2, 1, NOW());

-- ============================================================
-- teacher_class 关联:
--   - 公共教研室教师 (15 位): 挂全部 33 个 22 级班级
--                          (体现"服务全院"的公共教研室定位, 让 grade 筛选可见)
--   - 专业课教师 (100 位): 挂本专业 1-2 个班级
-- ============================================================
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (700, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (701, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (702, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (703, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (704, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (705, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (706, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (707, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (708, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (709, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (710, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (711, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (712, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (713, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (714, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (715, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (715, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (716, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (716, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (717, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (717, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (718, 200);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (718, 201);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (719, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (720, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (721, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (722, 216);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (723, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (724, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (725, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (726, 217);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (727, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (728, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (729, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (730, 218);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (731, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (731, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (732, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (732, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (733, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (733, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (734, 202);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (734, 203);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (735, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (735, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (736, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (736, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (737, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (737, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (738, 204);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (738, 205);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (739, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (740, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (741, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (742, 219);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (743, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (743, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (744, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (744, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (745, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (745, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (746, 206);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (746, 207);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (747, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (748, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (749, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (750, 220);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (751, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (752, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (753, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (754, 221);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (755, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (755, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (756, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (756, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (757, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (757, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (758, 208);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (758, 209);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (759, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (759, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (760, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (760, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (761, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (761, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (762, 210);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (762, 211);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (763, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (764, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (765, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (766, 222);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (767, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (768, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (769, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (770, 223);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (771, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (772, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (773, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (774, 224);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (775, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (776, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (777, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (778, 225);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (779, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (780, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (781, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (782, 226);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (783, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (784, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (785, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (786, 227);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (787, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (787, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (788, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (788, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (789, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (789, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (790, 212);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (790, 213);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (791, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (792, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (793, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (794, 228);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (795, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (796, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (797, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (798, 229);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (799, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (799, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (800, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (800, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (801, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (801, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (802, 214);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (802, 215);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (803, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (804, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (805, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (806, 230);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (807, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (808, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (809, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (810, 231);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (811, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (812, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (813, 232);
INSERT INTO teacher_class (teacher_id, class_id) VALUES (814, 232);

COMMIT;
SET FOREIGN_KEY_CHECKS = 1;


-- ============= 验证 =============
SELECT '22级新增教师数 (期望 115)' AS metric, COUNT(*) AS actual FROM sys_user WHERE id BETWEEN 700 AND 814 AND role_id=2;
SELECT m.id AS '专业ID', m.major_name AS '专业', COUNT(DISTINCT tc.teacher_id) AS '专业课教师数'
  FROM teacher_class tc JOIN edu_class c ON tc.class_id=c.id JOIN edu_major m ON c.major_id=m.id
  WHERE tc.teacher_id BETWEEN 700 AND 814
  GROUP BY m.id ORDER BY m.id;