-- ============================================================================
-- 自动生成 (工具_生成22级用户.py) — 请勿手工修改
-- ============================================================================
USE online_exam_system;
SET FOREIGN_KEY_CHECKS = 0;
START TRANSACTION;

-- 幂等：清理 22 级任课后再写入（允许重复执行；与 14 号 24 级数据互不干扰）
DELETE ts FROM teacher_subject ts
INNER JOIN edu_subject s ON s.id = ts.subject_id
WHERE s.grade = '2022级';

-- ============================================================
-- teacher_subject 任课关系 (按课程类别精准分配)
--
-- 课程类别统计:
--   daxue_wuli             24 门 → 公共池 2 位
--   daxue_yingyu          104 门 → 公共池 3 位
--   daxue_yuwen             8 门 → 公共池 1 位
--   gailv                  12 门 → 公共池 1 位
--   gongshu_A              24 门 → 公共池 2 位
--   gongshu_B              16 门 → 公共池 2 位
--   gongshu_C               3 门 → 公共池 1 位
--   jichu_riyu_gong         4 门 → 公共池 2 位
--   junshi                 28 门 → 公共池 1 位
--   linear_algebra         20 门 → 公共池 1 位
--   sizheng               140 门 → 公共池 5 位
--   xinli_jiuye            56 门 → 公共池 2 位
--   zhuanye               298 门 → 专业课 (25 专业 × 4 教师)
-- ============================================================

-- ---- 公共课任课 ----
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (14, 138); -- [zhuanye_luwei] 面向对象技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (14, 145); -- [zhuanye_luwei] Java EE 开发技术基础
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 114); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 115); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 116); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 117); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 118); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 123); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 124); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 125); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 126); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 127); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 128); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 129); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 130); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 131); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 132); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 133); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 134); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 135); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 215); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 216); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 217); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 218); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 219); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 224); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 225); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 226); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 227); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 228); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 229); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 230); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 231); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 232); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 233); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 234); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 235); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 236); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 282); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 283); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 284); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 285); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 286); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 291); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 292); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 293); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 294); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 295); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 296); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 297); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 298); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 299); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 300); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 301); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 302); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 303); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 347); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 348); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 349); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 350); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 351); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 356); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 357); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 358); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 359); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 360); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 361); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 362); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 363); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 364); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 365); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 366); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 367); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 368); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 412); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 413); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 414); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 415); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 416); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 421); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 422); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 423); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 424); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 425); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 426); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 427); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 428); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 429); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 430); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 431); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 432); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 433); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 479); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 480); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 481); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 482); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 483); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 488); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 489); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 490); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 491); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 492); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 493); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 494); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 495); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 496); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 497); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 498); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 499); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 500); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 546); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 547); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 548); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 549); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 550); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 555); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 556); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 557); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (713, 558); -- [daxue_yuwen] 大学语文
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (106, 560); -- [jichu_riyu_gong] 基础日语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (120, 561); -- [jichu_riyu_gong] 基础日语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (106, 562); -- [jichu_riyu_gong] 日语听力(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (120, 563); -- [jichu_riyu_gong] 日语听力(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 597); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 598); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 599); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 600); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 601); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 606); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 607); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 608); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (713, 609); -- [daxue_yuwen] 大学语文
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 654); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 655); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 656); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 657); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 658); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 663); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 664); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 665); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 666); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 667); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 668); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 669); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (710, 670); -- [gongshu_C] 高等数学C
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (713, 671); -- [daxue_yuwen] 大学语文
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 713); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 714); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 715); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 716); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 717); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 722); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 723); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 724); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 725); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 726); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 727); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 728); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (710, 729); -- [gongshu_C] 高等数学C
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (713, 730); -- [daxue_yuwen] 大学语文
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 770); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 771); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 772); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 773); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 774); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 779); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 780); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 781); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 782); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 783); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 784); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 785); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 786); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 787); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 788); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 789); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 790); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 791); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 835); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 836); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 837); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 838); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 839); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 844); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 845); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 846); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 847); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 848); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 849); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 850); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 851); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 852); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 853); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 854); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 855); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 856); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 902); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 903); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 904); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 905); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 906); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 911); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 912); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 913); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 914); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 915); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 916); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 917); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 918); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 919); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 920); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 921); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 922); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 923); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 969); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 970); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 971); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 972); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 973); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 978); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 979); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 980); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 981); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 982); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 983); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 984); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 985); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 986); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 987); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 988); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 989); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 990); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1036); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1037); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1038); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1039); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1040); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1045); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1046); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1047); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1048); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1049); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1050); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1051); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (710, 1052); -- [gongshu_C] 高等数学C
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (713, 1053); -- [daxue_yuwen] 大学语文
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1093); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1094); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1095); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1096); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1097); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1102); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1103); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1104); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1105); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1106); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1107); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1108); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (708, 1109); -- [gongshu_B] 高等数学B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (709, 1110); -- [gongshu_B] 高等数学B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1111); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1156); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1157); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1158); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1159); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1160); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1165); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1166); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1167); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1168); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1169); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1170); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1171); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (708, 1172); -- [gongshu_B] 高等数学B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (709, 1173); -- [gongshu_B] 高等数学B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1174); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1221); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1222); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1223); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1224); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1225); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1230); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1231); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1232); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1233); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1234); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1235); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1236); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (708, 1237); -- [gongshu_B] 高等数学B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (709, 1238); -- [gongshu_B] 高等数学B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1239); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1286); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1287); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1288); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1289); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1290); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1295); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1296); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1297); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1298); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1299); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1300); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1301); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (708, 1302); -- [gongshu_B] 高等数学B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (709, 1303); -- [gongshu_B] 高等数学B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1304); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1351); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1352); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1353); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1354); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1355); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1360); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1361); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1362); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1363); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1364); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1365); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1366); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (708, 1367); -- [gongshu_B] 高等数学B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (709, 1368); -- [gongshu_B] 高等数学B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1369); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1416); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1417); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1418); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1419); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1420); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1425); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1426); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1427); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1428); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1429); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1430); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1431); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (708, 1432); -- [gongshu_B] 高等数学B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (709, 1433); -- [gongshu_B] 高等数学B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1434); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1481); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1482); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1483); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1484); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1485); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1490); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1491); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1492); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1493); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1494); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1495); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1496); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (708, 1497); -- [gongshu_B] 高等数学B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (709, 1498); -- [gongshu_B] 高等数学B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1499); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1546); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1547); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1548); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1549); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1550); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1555); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1556); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1557); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1558); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1559); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1560); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1561); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (713, 1562); -- [daxue_yuwen] 大学语文
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1605); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1606); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1607); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1608); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1609); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1614); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1615); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1616); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1617); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1618); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1619); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1620); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (713, 1621); -- [daxue_yuwen] 大学语文
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1664); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1665); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1666); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1667); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1668); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1673); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1674); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1675); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1676); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1677); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1678); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1679); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (713, 1680); -- [daxue_yuwen] 大学语文
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1723); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1724); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1725); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1726); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1727); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1732); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1733); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1734); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1735); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1736); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1737); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1738); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 1739); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 1740); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1741); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1742); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 1743); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 1744); -- [daxue_wuli] 大学物理B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1796); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1797); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1798); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1799); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1800); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1805); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1806); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1807); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1808); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1809); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1810); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1811); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (708, 1812); -- [gongshu_B] 高等数学B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (709, 1813); -- [gongshu_B] 高等数学B(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1814); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (700, 1863); -- [sizheng] 思想道德与法治
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (701, 1864); -- [sizheng] 中国近现代史纲要
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (702, 1865); -- [sizheng] 马克思主义基本原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (703, 1866); -- [sizheng] 毛泽东思想和中国特色社会主义理论体系概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (704, 1867); -- [sizheng] 形势与政策
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (705, 1872); -- [junshi] 军事理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (706, 1873); -- [xinli_jiuye] 心理健康教育
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (707, 1874); -- [xinli_jiuye] 大学生职业发展与就业指导
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1875); -- [daxue_yingyu] 大学英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (122, 1876); -- [daxue_yingyu] 大学英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (107, 1877); -- [daxue_yingyu] 大学英语(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (119, 1878); -- [daxue_yingyu] 大学英语(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (100, 1879); -- [gongshu_A] 高等数学A(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (104, 1880); -- [gongshu_A] 高等数学A(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1881); -- [linear_algebra] 线性代数
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (123, 1882); -- [gailv] 概率论与数理统计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (711, 1883); -- [daxue_wuli] 大学物理B(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (712, 1884); -- [daxue_wuli] 大学物理B(二)

-- ---- 专业课任课 ----
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (715, 137); -- [major=100] 离散结构
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (716, 139); -- [major=100] 算法与程序设计基础
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (717, 140); -- [major=100] 数据结构
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (718, 141); -- [major=100] 数据库原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (715, 142); -- [major=100] 计算机组成原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (716, 143); -- [major=100] 操作系统
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (717, 144); -- [major=100] 计算机网络原理及工程应用
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (718, 146); -- [major=100] 软件工程
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (715, 147); -- [major=100] 编译原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (716, 148); -- [major=100] 人工智能基础
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (717, 149); -- [major=100] 基于.Net的应用开发技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (718, 150); -- [major=100] 移动互联网开发技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (715, 151); -- [major=100] 物联网与嵌入式系统开发
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (716, 152); -- [major=100] 软件建模与分析
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (717, 153); -- [major=100] 软件质量保证与测试
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (718, 154); -- [major=100] 信息安全技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (715, 155); -- [major=100] 智能技术应用与开发
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (719, 238); -- [major=101] 电路分析
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (720, 239); -- [major=101] 模拟电子技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (721, 240); -- [major=101] 数字电子技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (722, 241); -- [major=101] 信号与系统
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (719, 242); -- [major=101] 通信原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (720, 243); -- [major=101] 数字信号处理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (721, 244); -- [major=101] 电磁场与电磁波
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (722, 245); -- [major=101] 移动通信
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (719, 246); -- [major=101] 光纤通信
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (723, 305); -- [major=102] 电路分析
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (724, 306); -- [major=102] 模拟电子技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (725, 307); -- [major=102] 数字电子技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (726, 308); -- [major=102] 信号与系统
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (723, 309); -- [major=102] 微机原理及接口技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (724, 310); -- [major=102] 数字信号处理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (725, 311); -- [major=102] 传感器与检测技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (726, 312); -- [major=102] 嵌入式系统
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (727, 370); -- [major=103] 工程制图
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (728, 371); -- [major=103] 理论力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (729, 372); -- [major=103] 材料力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (730, 373); -- [major=103] 机械原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (727, 374); -- [major=103] 机械设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (728, 375); -- [major=103] 机械制造技术基础
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (729, 376); -- [major=103] 数控技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (730, 377); -- [major=103] 液压与气压传动
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (731, 435); -- [major=104] 电路分析
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (732, 436); -- [major=104] 模拟电子技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (733, 437); -- [major=104] 数字电子技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (734, 438); -- [major=104] 自动控制原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (731, 439); -- [major=104] 电机学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (732, 440); -- [major=104] 电力电子技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (733, 441); -- [major=104] 电力系统分析
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (734, 442); -- [major=104] 电力拖动与运动控制
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (731, 443); -- [major=104] 继电保护
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (735, 502); -- [major=105] 工程制图
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (736, 503); -- [major=105] 理论力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (737, 504); -- [major=105] 材料力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (738, 505); -- [major=105] 结构力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (735, 506); -- [major=105] 土力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (736, 507); -- [major=105] 混凝土结构设计原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (737, 508); -- [major=105] 钢结构设计原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (738, 509); -- [major=105] 土木工程施工
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (735, 510); -- [major=105] 基础工程
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (739, 559); -- [major=106] 第二外语(英语)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (740, 564); -- [major=106] 日语口语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (741, 565); -- [major=106] 日语口语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (742, 566); -- [major=106] 高级日语
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (739, 567); -- [major=106] 日汉翻译理论与实践
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (740, 568); -- [major=106] 日本文学史
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (741, 569); -- [major=106] 日本概况
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (743, 610); -- [major=107] 第二外语(英语)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (744, 611); -- [major=107] 综合英语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (745, 612); -- [major=107] 综合英语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (746, 613); -- [major=107] 英语听力(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (743, 614); -- [major=107] 英语听力(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (744, 615); -- [major=107] 英语口语(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (745, 616); -- [major=107] 英语口语(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (746, 617); -- [major=107] 英语语法
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (743, 618); -- [major=107] 英语阅读
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (744, 619); -- [major=107] 英语写作
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (745, 620); -- [major=107] 高级英语
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (746, 621); -- [major=107] 英汉翻译理论与实践
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (743, 622); -- [major=107] 英美文学史
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (744, 623); -- [major=107] 语言学概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (747, 672); -- [major=108] 现代汉语
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (748, 673); -- [major=108] 古代汉语
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (749, 674); -- [major=108] 中国古代文学(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (750, 675); -- [major=108] 中国古代文学(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (747, 676); -- [major=108] 中国现代文学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (748, 677); -- [major=108] 中国当代文学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (749, 678); -- [major=108] 外国文学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (750, 679); -- [major=108] 文学概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (747, 680); -- [major=108] 语言学概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (748, 681); -- [major=108] 中国文化概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (751, 731); -- [major=109] 秘书学概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (752, 732); -- [major=109] 应用写作
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (753, 733); -- [major=109] 现代汉语
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (754, 734); -- [major=109] 管理学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (751, 735); -- [major=109] 公共关系学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (752, 736); -- [major=109] 秘书实务
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (753, 737); -- [major=109] 办公自动化
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (754, 738); -- [major=109] 档案管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (751, 739); -- [major=109] 商务谈判与礼仪
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (755, 793); -- [major=110] 无机及分析化学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (756, 794); -- [major=110] 有机化学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (757, 795); -- [major=110] 环境工程微生物学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (758, 796); -- [major=110] 环境监测
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (755, 797); -- [major=110] 水污染控制工程
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (756, 798); -- [major=110] 大气污染控制工程
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (757, 799); -- [major=110] 固体废物处理与处置
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (758, 800); -- [major=110] 环境影响评价
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (759, 858); -- [major=111] 工程制图
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (760, 859); -- [major=111] 水力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (761, 860); -- [major=111] 水分析化学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (762, 861); -- [major=111] 水文学与水文地质
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (759, 862); -- [major=111] 水处理生物学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (760, 863); -- [major=111] 水质工程学(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (761, 864); -- [major=111] 水质工程学(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (762, 865); -- [major=111] 给水排水管网系统
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (759, 866); -- [major=111] 建筑给水排水工程
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (763, 925); -- [major=112] 工程制图
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (764, 926); -- [major=112] 流体力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (765, 927); -- [major=112] 工程热力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (766, 928); -- [major=112] 传热学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (763, 929); -- [major=112] 建筑环境学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (764, 930); -- [major=112] 流体输配管网
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (765, 931); -- [major=112] 暖通空调
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (766, 932); -- [major=112] 冷热源工程
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (763, 933); -- [major=112] 建筑设备自动化
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (767, 992); -- [major=113] 园林美术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (768, 993); -- [major=113] 园林制图
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (769, 994); -- [major=113] 园林树木学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (770, 995); -- [major=113] 园林花卉学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (767, 996); -- [major=113] 园林生态学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (768, 997); -- [major=113] 园林规划设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (769, 998); -- [major=113] 中外园林史
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (770, 999); -- [major=113] 园林植物造景
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (767, 1000); -- [major=113] 园林工程
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (771, 1054); -- [major=114] 自然地理学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (772, 1055); -- [major=114] 人文地理学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (773, 1056); -- [major=114] 经济地理学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (774, 1057); -- [major=114] 地图学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (771, 1058); -- [major=114] GIS原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (772, 1059); -- [major=114] 城市规划原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (773, 1060); -- [major=114] 城市规划设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (774, 1061); -- [major=114] 土地利用规划
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (771, 1062); -- [major=114] 区域分析与规划
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (775, 1112); -- [major=115] 经济应用统计学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (776, 1113); -- [major=115] 管理学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (777, 1114); -- [major=115] 微观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (778, 1115); -- [major=115] 宏观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (775, 1116); -- [major=115] 会计学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (776, 1117); -- [major=115] 工程力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (777, 1118); -- [major=115] 工程经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (778, 1119); -- [major=115] 建筑工程技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (775, 1120); -- [major=115] 工程项目管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (776, 1121); -- [major=115] 工程招投标与合同管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (777, 1122); -- [major=115] 工程造价管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (779, 1175); -- [major=116] 经济应用统计学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (780, 1176); -- [major=116] 管理学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (781, 1177); -- [major=116] 微观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (782, 1178); -- [major=116] 会计学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (779, 1179); -- [major=116] 工程经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (780, 1180); -- [major=116] 建筑制图
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (781, 1181); -- [major=116] 建筑材料
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (782, 1182); -- [major=116] 建筑工程计量与计价
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (779, 1183); -- [major=116] 安装工程计量与计价
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (780, 1184); -- [major=116] 工程项目管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (781, 1185); -- [major=116] 工程招投标与合同管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (782, 1186); -- [major=116] 工程造价信息化
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (783, 1240); -- [major=117] 经济应用统计学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (784, 1241); -- [major=117] 管理学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (785, 1242); -- [major=117] 微观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (786, 1243); -- [major=117] 宏观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (783, 1244); -- [major=117] 会计学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (784, 1245); -- [major=117] 市场营销学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (785, 1246); -- [major=117] 消费者行为学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (786, 1247); -- [major=117] 市场调查与预测
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (783, 1248); -- [major=117] 销售管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (784, 1249); -- [major=117] 品牌管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (785, 1250); -- [major=117] 数字营销
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (786, 1251); -- [major=117] 国际市场营销
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (787, 1305); -- [major=118] 经济应用统计学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (788, 1306); -- [major=118] 管理学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (789, 1307); -- [major=118] 微观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (790, 1308); -- [major=118] 宏观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (787, 1309); -- [major=118] 会计学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (788, 1310); -- [major=118] 中级财务会计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (789, 1311); -- [major=118] 财务管理学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (790, 1312); -- [major=118] 管理会计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (787, 1313); -- [major=118] 税法
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (788, 1314); -- [major=118] 高级财务管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (789, 1315); -- [major=118] 审计学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (790, 1316); -- [major=118] 公司战略与风险管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (791, 1370); -- [major=119] 经济应用统计学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (792, 1371); -- [major=119] 管理学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (793, 1372); -- [major=119] 微观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (794, 1373); -- [major=119] 组织行为学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (791, 1374); -- [major=119] 会计学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (792, 1375); -- [major=119] 人力资源管理概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (793, 1376); -- [major=119] 劳动经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (794, 1377); -- [major=119] 招聘与配置
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (791, 1378); -- [major=119] 绩效管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (792, 1379); -- [major=119] 薪酬管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (793, 1380); -- [major=119] 培训与开发
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (794, 1381); -- [major=119] 劳动关系管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (795, 1435); -- [major=120] 经济应用统计学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (796, 1436); -- [major=120] 管理学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (797, 1437); -- [major=120] 微观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (798, 1438); -- [major=120] 旅游学概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (795, 1439); -- [major=120] 会计学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (796, 1440); -- [major=120] 酒店管理概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (797, 1441); -- [major=120] 前厅服务与管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (798, 1442); -- [major=120] 客房服务与管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (795, 1443); -- [major=120] 餐饮服务与管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (796, 1444); -- [major=120] 酒店人力资源管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (797, 1445); -- [major=120] 酒店营销管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (798, 1446); -- [major=120] 酒店财务管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (799, 1500); -- [major=121] 经济应用统计学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (800, 1501); -- [major=121] 管理学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (801, 1502); -- [major=121] 微观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (802, 1503); -- [major=121] 会计学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (799, 1504); -- [major=121] 物流学概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (800, 1505); -- [major=121] 运筹学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (801, 1506); -- [major=121] 供应链管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (802, 1507); -- [major=121] 仓储管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (799, 1508); -- [major=121] 运输管理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (800, 1509); -- [major=121] 物流信息系统
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (801, 1510); -- [major=121] 国际物流
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (802, 1511); -- [major=121] 物流系统规划
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (803, 1563); -- [major=122] 艺术概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (804, 1564); -- [major=122] 设计素描
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (805, 1565); -- [major=122] 设计色彩
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (806, 1566); -- [major=122] 三大构成
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (803, 1567); -- [major=122] 中外设计史
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (804, 1568); -- [major=122] 图形创意
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (805, 1569); -- [major=122] 字体与版式设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (806, 1570); -- [major=122] VI设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (803, 1571); -- [major=122] 包装设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (804, 1572); -- [major=122] 广告设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (805, 1573); -- [major=122] UI界面设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (807, 1622); -- [major=123] 艺术概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (808, 1623); -- [major=123] 设计素描
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (809, 1624); -- [major=123] 设计色彩
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (810, 1625); -- [major=123] 三大构成
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (807, 1626); -- [major=123] 中外建筑史
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (808, 1627); -- [major=123] 环境设计制图
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (809, 1628); -- [major=123] 室内设计原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (810, 1629); -- [major=123] 家具设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (807, 1630); -- [major=123] 景观设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (808, 1631); -- [major=123] 展示设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (809, 1632); -- [major=123] 公共空间设计
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (811, 1681); -- [major=124] 艺术概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (812, 1682); -- [major=124] 乐理与视唱练耳
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (813, 1683); -- [major=124] 中国音乐史
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (814, 1684); -- [major=124] 西方音乐史
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (811, 1685); -- [major=124] 和声学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (812, 1686); -- [major=124] 曲式与作品分析
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (813, 1687); -- [major=124] 乐器演奏(一)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (814, 1688); -- [major=124] 乐器演奏(二)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (811, 1689); -- [major=124] 乐器演奏(三)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (812, 1690); -- [major=124] 乐器演奏(四)
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (813, 1691); -- [major=124] 打击乐合奏
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (715, 1746); -- [major=125] 离散结构
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (716, 1747); -- [major=125] 面向对象技术
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (717, 1748); -- [major=125] 数据结构
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (718, 1749); -- [major=125] 数据库原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (715, 1750); -- [major=125] 操作系统
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (716, 1751); -- [major=125] 计算机网络
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (717, 1752); -- [major=125] Python数据分析
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (718, 1753); -- [major=125] 机器学习
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (715, 1754); -- [major=125] 大数据处理与Hadoop
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (716, 1755); -- [major=125] 深度学习
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (717, 1756); -- [major=125] 数据挖掘
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (718, 1757); -- [major=125] 数据可视化
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (799, 1815); -- [major=126] 经济应用统计学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (800, 1816); -- [major=126] 管理学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (801, 1817); -- [major=126] 微观经济学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (802, 1818); -- [major=126] 会计学原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (799, 1819); -- [major=126] 国际贸易理论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (800, 1820); -- [major=126] 市场营销学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (801, 1821); -- [major=126] 电子商务概论
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (802, 1822); -- [major=126] 跨境电商实务
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (799, 1823); -- [major=126] 国际物流与报关
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (800, 1824); -- [major=126] 外贸函电
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (801, 1825); -- [major=126] 跨境电商平台运营
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (802, 1826); -- [major=126] 跨境支付与结算
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (799, 1827); -- [major=126] 跨境电商数据分析
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (727, 1886); -- [major=127] 工程制图
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (728, 1887); -- [major=127] 理论力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (729, 1888); -- [major=127] 材料力学
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (730, 1889); -- [major=127] 机械原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (727, 1890); -- [major=127] 材料科学基础
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (728, 1891); -- [major=127] 增材制造原理
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (729, 1892); -- [major=127] 增材制造工艺
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (730, 1893); -- [major=127] 增材制造材料
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (727, 1894); -- [major=127] 逆向工程与3D建模
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (728, 1895); -- [major=127] 增材制造设备
INSERT INTO teacher_subject (teacher_id, subject_id) VALUES (729, 1896); -- [major=127] 快速成型与制造

COMMIT;
SET FOREIGN_KEY_CHECKS = 1;


-- ============= 验证 =============
SELECT '22 级任课关系数' AS metric, COUNT(*) AS actual
  FROM teacher_subject ts JOIN edu_subject s ON ts.subject_id=s.id
  WHERE s.grade='2022级';
SELECT u.real_name AS '教师', COUNT(ts.subject_id) AS '任课数'
  FROM sys_user u JOIN teacher_subject ts ON ts.teacher_id=u.id
  JOIN edu_subject s ON ts.subject_id=s.id
  WHERE s.grade='2022级' AND u.id BETWEEN 700 AND 824
  GROUP BY u.id ORDER BY COUNT(ts.subject_id) DESC LIMIT 20;