"""
Java v2.5 - subject increment

Target: baseline 90 -> 300 (delta 210)
Type breakdown: single 80 / multi 40 / judge 40 / fill 30 / essay 20

Knowledge points:
  Java 基础语法/面向对象/集合/异常/IO/多线程/反射/JVM/Lambda/Stream
"""

INCREMENTAL = [
    # ============ 单选题 80 道 ============
    # --- Java 基础语法 ---
    ("单选","Java 程序源文件的扩展名是",".java",".class",".exe",".jar","A","Java 源文件 .java,编译后 .class",2,"简单"),
    ("单选","Java 编译后生成的字节码文件扩展名是",".java",".class",".exe",".jar","B",".class 为字节码",2,"简单"),
    ("单选","JVM 的全称是","Java Virtual Machine","Java Visual Machine","Java Visual Model","Java Verify Machine","A","JVM:Java 虚拟机",2,"简单"),
    ("单选","JDK 的全称是","Java Development Kit","Java Dynamic Kit","Java Debug Kit","Java Distribution Kit","A","JDK 开发工具包",2,"简单"),
    ("单选","JRE 的全称是","Java Runtime Environment","Java Run Engine","Java Real Engine","Java Resource Environment","A","JRE 运行时环境",2,"简单"),
    ("单选","JDK、JRE、JVM 三者的关系正确的是","JDK ⊇ JRE ⊇ JVM","JRE ⊇ JDK ⊇ JVM","JVM ⊇ JRE ⊇ JDK","三者独立","A","JDK 包含 JRE,JRE 包含 JVM",2,"中等"),
    ("单选","下列哪个不是 Java 基本数据类型","int","String","boolean","char","B","String 是引用类型",2,"简单"),
    ("单选","Java 中 int 类型占多少字节","2","4","8","16","B","int=4 字节(32 位)",2,"简单"),
    ("单选","Java 中 long 类型占多少字节","2","4","8","16","C","long=8 字节",2,"简单"),
    ("单选","Java 中 double 类型占多少字节","2","4","8","16","C","double=8 字节",2,"简单"),
    ("单选","Java 中 char 类型占多少字节","1","2","4","8","B","char=2 字节(Unicode)",2,"中等"),
    ("单选","Java 中 boolean 类型的取值是","0/1","true/false","yes/no","TRUE/FALSE","B","boolean: true/false",2,"简单"),
    ("单选","下列哪个是 Java 的关键字","static","public","void","以上都是","D","三者都是关键字",2,"简单"),
    ("单选","Java 中 break 的作用是","跳出循环","继续循环","返回","退出程序","A","break 终止最近的循环",2,"简单"),
    ("单选","Java 中 continue 的作用是","跳出循环","跳过当前迭代","返回","退出程序","B","continue 跳过当前一次迭代",2,"简单"),
    ("单选","Java 程序入口方法的签名是","main()","public main()","public static void main(String[] args)","static main()","C","JVM 查找的入口方法签名",2,"中等"),
    ("单选","Java 中 String 是","基本类型","引用类型","原始类型","值类型","B","String 是引用类型",2,"简单"),
    ("单选","Java 中字符串拼接最优的方式是","+ 运算符","String.concat","StringBuilder","String.join","C","StringBuilder 在循环中性能最好",2,"中等"),
    ("单选","下列说法正确的是","String 可变","StringBuilder 不可变","StringBuffer 是线程安全的","三者都可变","C","String 不可变,StringBuilder 不安全,StringBuffer 安全",2,"中等"),
    ("单选","int i=10; i++ 的结果是 i 等于","9","10","11","12","C","i++ 是自增",2,"简单"),
    # --- 面向对象 ---
    ("单选","Java 中 OOP 不包括","封装","继承","多态","重载","D","重载是多态的体现,不是 OOP 三大特性",2,"中等"),
    ("单选","Java 中 OOP 的三大特性是","封装、继承、多态","封装、抽象、继承","继承、多态、接口","以上都不","A","OOP 三大特性",2,"简单"),
    ("单选","Java 中 class 的成员不包括","属性","方法","构造器","main 方法是必须的","D","class 不必须有 main",2,"中等"),
    ("单选","Java 中关键字 extends 的作用是","实现接口","继承类","包含包","导入类","B","extends 用于类的继承",2,"简单"),
    ("单选","Java 中关键字 implements 的作用是","实现接口","继承类","包含包","导入类","A","implements 用于实现接口",2,"简单"),
    ("单选","Java 中支持多继承吗","支持","不支持,但可实现多接口","支持类多继承","不支持任何多继承","B","Java 单继承,多接口实现",2,"中等"),
    ("单选","下列关于构造器描述错误的是","与类同名","没有返回类型","可以重载","可以被继承","D","构造器不能被继承",2,"中等"),
    ("单选","下列哪个是 Java 中所有类的父类","Object","String","Class","Super","A","Object 是所有类的超类",2,"中等"),
    ("单选","下列方法不是 Object 中的是","equals","hashCode","toString","main","D","main 不是 Object 方法",2,"中等"),
    ("单选","下列关于 this 的描述错误的是","this 指向当前对象","可以在静态方法中使用","可以调用当前对象的方法","可以在构造器中调用其他构造器","B","静态方法没有 this",2,"中等"),
    ("单选","下列关于 super 的描述错误的是","可以调用父类方法","可以调用父类构造器","可以在静态方法中使用","调用父类构造器必须在第一行","C","静态方法没有 super",2,"中等"),
    ("单选","下列关于 static 的描述错误的是","static 修饰的方法属于类","static 修饰的方法不能访问实例变量","static 方法可以被重写","static 块在类加载时执行","C","static 方法不能被重写(只能隐藏)",2,"困难"),
    ("单选","下列关于 final 的描述错误的是","final 修饰的类不能继承","final 修饰的方法不能重写","final 修饰的变量不能修改","final 修饰的方法不能被继承","D","final 方法可以被继承,只是不能重写",2,"困难"),
    ("单选","下列关于 abstract 的描述错误的是","abstract 类不能实例化","abstract 类可以有非抽象方法","abstract 方法没有方法体","abstract 类必须有 abstract 方法","D","abstract 类可以没有抽象方法",2,"困难"),
    ("单选","下列关于接口描述错误的是","接口不能被实例化","接口中的方法默认 public abstract","Java 8 接口可以有 default 方法","接口可以有构造方法","D","接口不能有构造器",2,"中等"),
    ("单选","下列哪个修饰符表示包内可见","public","protected","private","默认(无)","D","默认即包内可见",2,"中等"),
    ("单选","下列修饰符可见性最高的是","public","protected","private","默认","A","public 最公开",2,"简单"),
    ("单选","下列修饰符可见性最低的是","public","protected","private","默认","C","private 类内可见",2,"简单"),
    ("单选","方法重载 overload 的条件是","方法名相同,参数不同","方法名不同","方法名和参数都相同","参数和返回类型不同","A","重载:同名不同参",2,"中等"),
    ("单选","方法重写 override 的条件是","子类方法签名和父类相同","子类方法名和父类不同","子类方法参数和父类不同","子类返回值类型与父类不同","A","重写:同签名(返回类型可协变)",2,"中等"),
    # --- 集合 ---
    ("单选","Java 集合框架的顶层接口是","Collection","List","Set","Map","A","Collection 是顶层接口(Map 独立)",2,"中等"),
    ("单选","下列不属于 List 实现类的是","ArrayList","LinkedList","Vector","HashSet","D","HashSet 是 Set 实现",2,"中等"),
    ("单选","下列不属于 Set 实现类的是","HashSet","TreeSet","LinkedHashSet","ArrayList","D","ArrayList 是 List",2,"中等"),
    ("单选","下列不属于 Map 实现类的是","HashMap","TreeMap","LinkedHashMap","ArrayList","D","ArrayList 是 List",2,"中等"),
    ("单选","ArrayList 的底层实现是","数组","链表","双向链表","哈希表","A","ArrayList:动态数组",2,"中等"),
    ("单选","LinkedList 的底层实现是","数组","单链表","双向链表","哈希表","C","LinkedList:双向链表",2,"中等"),
    ("单选","HashMap 的底层实现(JDK 8+)是","数组+链表","数组+链表+红黑树","数组+红黑树","哈希表","B","JDK 8 后引入红黑树",2,"困难"),
    ("单选","HashMap 默认初始容量是","8","16","32","64","B","默认 16",2,"中等"),
    ("单选","HashMap 默认负载因子是","0.5","0.75","1.0","0.6","B","默认 0.75",2,"中等"),
    ("单选","下列哪个是线程安全的 Map","HashMap","TreeMap","LinkedHashMap","ConcurrentHashMap","D","并发 Map",2,"中等"),
    ("单选","HashSet 是基于哪个集合实现的","HashMap","ArrayList","LinkedList","TreeMap","A","HashSet 内部用 HashMap",2,"困难"),
    # --- 异常 ---
    ("单选","Java 中所有异常的父类是","Exception","Error","Throwable","RuntimeException","C","Throwable 是顶层",2,"中等"),
    ("单选","下列哪个是受检异常","NullPointerException","ArithmeticException","IOException","ClassCastException","C","IOException 是 Checked",2,"中等"),
    ("单选","下列哪个是非受检异常","IOException","SQLException","NullPointerException","ClassNotFoundException","C","NPE 是 RuntimeException",2,"中等"),
    ("单选","try-catch-finally 中,finally 一定会执行吗","一定","不一定,System.exit() 会跳过","只有 try 抛异常才执行","只有 catch 抛异常才执行","B","System.exit 会导致 finally 跳过",2,"困难"),
    ("单选","下列 throw 与 throws 描述正确的是","throw 用于声明异常,throws 用于抛出","throw 用于抛出,throws 用于声明","二者等价","二者无关","B","throw 抛,throws 声明",2,"中等"),
    ("单选","下列哪个是 RuntimeException 的子类","IOException","SQLException","NullPointerException","Exception","C","NPE 属于 RuntimeException",2,"中等"),
    # --- IO ---
    ("单选","Java IO 流分类按数据单位分","字节流和字符流","输入流和输出流","节点流和处理流","以上都对","A","字节流(byte) vs 字符流(char)",2,"中等"),
    ("单选","Java IO 流分类按流向分","字节流和字符流","输入流和输出流","节点流和处理流","以上都对","B","输入 vs 输出",2,"中等"),
    ("单选","FileInputStream 属于","字节输入流","字符输入流","字节输出流","字符输出流","A","Stream 字节,Reader/Writer 字符",2,"中等"),
    ("单选","BufferedReader 属于","字节输入流","字符输入流","字节输出流","字符输出流","B","Buffered Reader 字符",2,"中等"),
    ("单选","下列哪个不是 NIO 三大核心","Channel","Buffer","Selector","Stream","D","NIO 不用 Stream",2,"困难"),
    # --- 多线程 ---
    ("单选","Java 中创建线程的方式不包括","继承 Thread 类","实现 Runnable 接口","实现 Callable 接口","实现 Cloneable 接口","D","Cloneable 用于克隆",2,"中等"),
    ("单选","下列启动线程的方法是","start()","run()","init()","execute()","A","start 触发新线程,run 直接调用是普通方法",2,"中等"),
    ("单选","下列哪个是线程的状态","NEW","RUNNABLE","BLOCKED","以上都是","D","Java 线程 6 个状态",2,"中等"),
    ("单选","Java 中 synchronized 不能修饰","成员方法","静态方法","代码块","构造器","D","synchronized 不能修饰构造器",2,"困难"),
    ("单选","下列哪个不是 ReentrantLock 的特性","可重入","可中断","公平/非公平","内置(无需手动释放)","D","ReentrantLock 必须手动 unlock",2,"困难"),
    ("单选","volatile 关键字保证的特性是","原子性","可见性和有序性","可见性和原子性","原子性和有序性","B","volatile:可见性+禁止重排序",2,"困难"),
    ("单选","下列关于线程池描述错误的是","可以减少线程创建销毁开销","可以控制并发数","线程池总是越大越好","ThreadPoolExecutor 是 JUC 提供","C","线程池过大也会有问题",2,"中等"),
    ("单选","Executors 提供的方法不包括","newFixedThreadPool","newCachedThreadPool","newSingleThreadExecutor","newPriorityThreadPool","D","Executors 没有 priority 池",2,"困难"),
    ("单选","下列哪个不是 JUC 工具","CountDownLatch","CyclicBarrier","Semaphore","ConcurrentList","D","没有 ConcurrentList",2,"困难"),
    ("单选","Object 类中用于线程通信的方法不包括","wait()","notify()","notifyAll()","sleep()","D","sleep 是 Thread 的方法",2,"中等"),
    ("单选","下列哪个会释放锁","sleep","yield","wait","notify","C","wait 会释放锁",2,"困难"),
    # --- JVM ---
    ("单选","JVM 内存区域不包括","堆","栈","方法区","队列","D","没有队列区",2,"中等"),
    ("单选","下列内存区域线程私有的是","堆","方法区","虚拟机栈","直接内存","C","栈/PC/本地栈 线程私有",2,"困难"),
    ("单选","下列内存区域线程共享的是","堆","虚拟机栈","程序计数器","本地方法栈","A","堆和方法区共享",2,"困难"),
    ("单选","下列 GC 算法属于复制算法的是","标记-清除","标记-整理","复制","分代","C","复制算法",2,"中等"),
    ("单选","JDK 8 永久代被替换为","元空间 Metaspace","直接内存","新生代","老年代","A","JDK 8 永久代→元空间",2,"困难"),
    ("单选","下列哪个不是垃圾回收器","Serial","Parallel","CMS","Hotspot","D","Hotspot 是 JVM 实现",2,"困难"),
    ("单选","双亲委派模型的目的是","加快加载","避免重复加载和保证安全","节省内存","提高性能","B","委派给父加载器,避免类污染",2,"困难"),
    ("单选","下列 ClassLoader 不存在的是","Bootstrap","Extension","System/App","Module","D","Module 不是类加载器(JDK 9 引入模块系统)",2,"困难"),
    # ============ 多选题 40 道 ============
    ("多选","Java 的基本数据类型包括","int","double","char","boolean","A,B,C,D","8 种基本类型: byte,short,int,long,float,double,char,boolean",3,"简单"),
    ("多选","OOP 的三大特性包括","封装","继承","多态","重载","A,B,C","三大特性",3,"中等"),
    ("多选","下列属于 Java 关键字的是","class","interface","extends","implements","A,B,C,D","均为关键字",3,"简单"),
    ("多选","下列属于访问修饰符的是","public","protected","private","默认","A,B,C,D","Java 四种访问级别",3,"中等"),
    ("多选","下列说法正确的是","String 不可变","StringBuilder 可变","StringBuffer 线程安全","StringBuilder 线程安全","A,B,C","StringBuilder 非线程安全",3,"中等"),
    ("多选","下列方法是 Object 类的","equals","hashCode","toString","getClass","A,B,C,D","均为 Object 方法",3,"中等"),
    ("多选","下列说法正确的是","interface 不能实例化","abstract class 不能实例化","abstract class 可有具体方法","interface 不能有方法体","A,B,C","Java 8+ interface 可以 default 方法",3,"困难"),
    ("多选","下列属于 List 实现的是","ArrayList","LinkedList","Vector","Stack","A,B,C,D","均为 List 实现",3,"中等"),
    ("多选","下列属于 Set 实现的是","HashSet","TreeSet","LinkedHashSet","CopyOnWriteArraySet","A,B,C,D","均为 Set",3,"中等"),
    ("多选","下列属于 Map 实现的是","HashMap","TreeMap","LinkedHashMap","ConcurrentHashMap","A,B,C,D","均为 Map",3,"中等"),
    ("多选","HashMap 的特性包括","非线程安全","允许 null 键值","底层数组+链表+红黑树","有序","A,B,C","HashMap 无序",3,"困难"),
    ("多选","下列属于 Java 异常体系的是","Throwable","Error","Exception","RuntimeException","A,B,C,D","Java 异常体系",3,"中等"),
    ("多选","下列属于受检异常的是","IOException","SQLException","FileNotFoundException","ClassNotFoundException","A,B,C,D","均为 checked",3,"困难"),
    ("多选","下列属于非受检异常(RuntimeException)的是","NullPointerException","ArrayIndexOutOfBoundsException","ClassCastException","ArithmeticException","A,B,C,D","均为 RuntimeException 子类",3,"中等"),
    ("多选","下列属于字节流的是","FileInputStream","FileOutputStream","BufferedInputStream","DataInputStream","A,B,C,D","均为 Stream(字节)",3,"中等"),
    ("多选","下列属于字符流的是","FileReader","FileWriter","BufferedReader","BufferedWriter","A,B,C,D","均为 Reader/Writer",3,"中等"),
    ("多选","NIO 的三大核心是","Channel","Buffer","Selector","Stream","A,B,C","NIO: 通道+缓冲区+选择器",3,"困难"),
    ("多选","下列哪些方式可创建线程","继承 Thread","实现 Runnable","实现 Callable","线程池","A,B,C,D","Java 创建线程的方式",3,"中等"),
    ("多选","Java 线程的 6 个状态包括","NEW","RUNNABLE","BLOCKED","TERMINATED","A,B,C,D","另有 WAITING、TIMED_WAITING",3,"困难"),
    ("多选","下列实现线程安全的方式是","synchronized","Lock","CAS","volatile","A,B,C","volatile 不保证原子性",3,"困难"),
    ("多选","下列哪些方法会让线程释放锁","wait","notify","sleep","yield","A","只有 wait 释放锁",3,"困难"),
    ("多选","下列属于 JUC 工具的是","CountDownLatch","CyclicBarrier","Semaphore","Phaser","A,B,C,D","均为 JUC 同步工具",3,"困难"),
    ("多选","下列属于 ConcurrentHashMap 的特性","线程安全","分段锁(JDK7)/CAS+synchronized(JDK8)","不允许 null","高并发","A,B,C,D","CHM 特性",3,"困难"),
    ("多选","ThreadPoolExecutor 的核心参数包括","corePoolSize","maximumPoolSize","keepAliveTime","workQueue","A,B,C,D","线程池 7 大参数中的关键 4 个",3,"困难"),
    ("多选","下列哪些属于 JVM 内存区域","堆","栈","方法区","程序计数器","A,B,C,D","JVM 五大内存区域",3,"中等"),
    ("多选","下列哪些区域线程私有","虚拟机栈","本地方法栈","程序计数器","堆","A,B,C","堆和方法区共享",3,"困难"),
    ("多选","下列 GC 算法包括","标记-清除","复制","标记-整理","分代","A,B,C,D","常见 GC 算法",3,"困难"),
    ("多选","下列 JVM 垃圾回收器包括","Serial","Parallel","CMS","G1","A,B,C,D","常见 GC 收集器",3,"困难"),
    ("多选","双亲委派的好处包括","避免类重复加载","保证安全","保证类唯一性","便于扩展","A,B,C","双亲委派 3 大好处",3,"困难"),
    ("多选","下列哪些是 Java 8 新特性","Lambda","Stream","接口默认方法","Optional","A,B,C,D","Java 8 经典新特性",3,"中等"),
    ("多选","下列属于 Stream 中间操作","filter","map","sorted","collect","A,B,C","collect 是终止操作",3,"困难"),
    ("多选","下列属于 Stream 终止操作","forEach","collect","count","reduce","A,B,C,D","终止操作触发流",3,"困难"),
    ("多选","Java 反射 API 包括","Class","Method","Field","Constructor","A,B,C,D","反射四大对象",3,"中等"),
    ("多选","Java 注解 @Annotation 可作用于","类","方法","字段","参数","A,B,C,D","ElementType 各种位置",3,"中等"),
    ("多选","下列属于 Java 设计原则的是","单一职责","开闭","里氏","依赖倒置","A,B,C,D","SOLID 中的部分",3,"困难"),
    ("多选","下列属于 GoF 设计模式","单例","工厂","观察者","策略","A,B,C,D","常用设计模式",3,"中等"),
    ("多选","下列属于 Java 序列化方式","Serializable","Externalizable","JSON","XML","A,B,C,D","各种序列化",3,"中等"),
    ("多选","下列哪些是 Java 内置注解","@Override","@Deprecated","@SuppressWarnings","@FunctionalInterface","A,B,C,D","JDK 内置注解",3,"中等"),
    ("多选","下列哪些是 Spring 框架的特性","IoC","AOP","声明式事务","MVC","A,B,C,D","Spring 核心特性",3,"中等"),
    ("多选","下列哪些是 Java 8 函数式接口","Function","Predicate","Consumer","Supplier","A,B,C,D","JDK 8 functional interfaces",3,"困难"),
    ("多选","下列哪些是 Spring Boot 的核心特性","自动配置","起步依赖","内嵌容器","Actuator","A,B,C,D","Spring Boot 四大核心",3,"中等"),
    # ============ 判断题 40 道 ============
    ("判断","Java 是平台无关的语言",None,None,None,None,"正确","Write Once, Run Anywhere",1,"简单"),
    ("判断","JVM 把字节码翻译成机器码执行",None,None,None,None,"正确","JIT 编译/解释执行",1,"中等"),
    ("判断","Java 中所有类都默认继承 Object",None,None,None,None,"正确","Object 是所有类的父类",1,"中等"),
    ("判断","Java 支持类的多继承",None,None,None,None,"错误","Java 单继承,接口可多实现",1,"简单"),
    ("判断","String 是 final 类,不能被继承",None,None,None,None,"正确","String 用 final 修饰",1,"中等"),
    ("判断","String 对象是不可变的",None,None,None,None,"正确","String 不可变,修改会创建新对象",1,"中等"),
    ("判断","StringBuilder 线程安全,StringBuffer 不安全",None,None,None,None,"错误","StringBuilder 不安全,StringBuffer 安全",1,"中等"),
    ("判断","equals 默认比较地址",None,None,None,None,"正确","Object 的 equals 是 == 比较",1,"中等"),
    ("判断","重写 equals 必须重写 hashCode",None,None,None,None,"正确","Hash 容器一致性要求",1,"困难"),
    ("判断","抽象类可以实例化",None,None,None,None,"错误","abstract 不能 new",1,"中等"),
    ("判断","接口可以有 main 方法",None,None,None,None,"正确","Java 8+ 接口可有 static main",1,"困难"),
    ("判断","final 修饰的方法不能被重写",None,None,None,None,"正确","final 方法禁止 override",1,"中等"),
    ("判断","static 方法可以被重写",None,None,None,None,"错误","static 方法只能被隐藏(hide)",1,"困难"),
    ("判断","构造器可以是 abstract",None,None,None,None,"错误","构造器不能 abstract",1,"困难"),
    ("判断","构造器可以是 static",None,None,None,None,"错误","构造器不能 static",1,"困难"),
    ("判断","Object 的 toString 默认返回类名@hashCode",None,None,None,None,"正确","默认实现",1,"中等"),
    ("判断","HashMap 是线程安全的",None,None,None,None,"错误","HashMap 非线程安全",1,"简单"),
    ("判断","ConcurrentHashMap 是线程安全的",None,None,None,None,"正确","CHM 并发安全",1,"中等"),
    ("判断","ArrayList 比 LinkedList 随机访问快",None,None,None,None,"正确","ArrayList 数组 O(1)",1,"中等"),
    ("判断","LinkedList 比 ArrayList 头部插入快",None,None,None,None,"正确","LinkedList 头插 O(1)",1,"中等"),
    ("判断","HashMap 允许 null 键",None,None,None,None,"正确","HashMap 允许 1 个 null key",1,"中等"),
    ("判断","ConcurrentHashMap 允许 null 键",None,None,None,None,"错误","CHM 不允许 null",1,"困难"),
    ("判断","try-finally 中 finally 一定会执行",None,None,None,None,"错误","System.exit 或 JVM 崩溃不执行",1,"困难"),
    ("判断","IOException 是 RuntimeException",None,None,None,None,"错误","IOException 是 checked",1,"中等"),
    ("判断","NullPointerException 是受检异常",None,None,None,None,"错误","NPE 是 RuntimeException",1,"中等"),
    ("判断","sleep 不会释放锁",None,None,None,None,"正确","sleep 持有锁睡眠",1,"中等"),
    ("判断","wait 必须在 synchronized 中调用",None,None,None,None,"正确","wait 必须持锁",1,"困难"),
    ("判断","start 方法会启动新线程",None,None,None,None,"正确","start 触发 run",1,"中等"),
    ("判断","调用 run 方法不会启动新线程",None,None,None,None,"正确","直接调 run 是普通方法",1,"中等"),
    ("判断","volatile 保证原子性",None,None,None,None,"错误","volatile 只保证可见性和有序性",1,"困难"),
    ("判断","synchronized 是可重入锁",None,None,None,None,"正确","synchronized 同一线程可重入",1,"困难"),
    ("判断","ReentrantLock 必须手动 unlock",None,None,None,None,"正确","必须 try-finally unlock",1,"中等"),
    ("判断","Java 中 finalize 方法在 GC 前调用",None,None,None,None,"正确","finalize 给对象自救机会",1,"困难"),
    ("判断","堆和方法区是线程共享的",None,None,None,None,"正确","共享区域",1,"困难"),
    ("判断","栈是线程私有的",None,None,None,None,"正确","虚拟机栈线程私有",1,"中等"),
    ("判断","JDK 8 永久代被元空间替代",None,None,None,None,"正确","Metaspace",1,"困难"),
    ("判断","Lambda 表达式可以替代匿名内部类",None,None,None,None,"正确","仅适用于函数式接口",1,"中等"),
    ("判断","Stream 操作不修改源集合",None,None,None,None,"正确","Stream 是 immutable",1,"中等"),
    ("判断","反射可以访问 private 成员",None,None,None,None,"正确","setAccessible(true)",1,"中等"),
    ("判断","注解可以在运行时被读取",None,None,None,None,"正确","RetentionPolicy.RUNTIME 时可读",1,"困难"),
    # ============ 填空题 30 道 ============
    ("填空","Java 源代码文件扩展名是____",None,None,None,None,".java","Java 源文件 .java",2,"简单"),
    ("填空","Java 编译后字节码文件扩展名是____",None,None,None,None,".class","字节码 .class",2,"简单"),
    ("填空","Java 虚拟机的英文缩写是____",None,None,None,None,"JVM","Java Virtual Machine",2,"简单"),
    ("填空","Java 中所有类的根类是____",None,None,None,None,"Object","Object 是顶层父类",2,"中等"),
    ("填空","int 类型在 Java 中占____字节",None,None,None,None,"4","int=4 字节(32 位)",2,"简单"),
    ("填空","Java 中 boolean 类型的取值是 true 和____",None,None,None,None,"false","boolean: true/false",2,"简单"),
    ("填空","Java 中创建对象的关键字是____",None,None,None,None,"new","new 关键字创建对象",2,"简单"),
    ("填空","Java 中表示当前对象的关键字是____",None,None,None,None,"this","this 引用当前对象",2,"简单"),
    ("填空","Java 中表示父类的关键字是____",None,None,None,None,"super","super 引用父类",2,"简单"),
    ("填空","Java 中类的继承使用关键字____",None,None,None,None,"extends","extends 用于继承",2,"简单"),
    ("填空","Java 中实现接口使用关键字____",None,None,None,None,"implements","implements 用于实现接口",2,"简单"),
    ("填空","Java 中表示抽象的关键字是____",None,None,None,None,"abstract","abstract 修饰抽象类/方法",2,"中等"),
    ("填空","Java 中 final 修饰的类不能被____",None,None,None,None,"继承","final 类禁止继承",2,"中等"),
    ("填空","Java 中所有异常的根类是____",None,None,None,None,"Throwable","Throwable 是顶层异常",2,"中等"),
    ("填空","Java 中包含 wait/notify 方法的类是____",None,None,None,None,"Object","wait/notify 是 Object 方法",2,"困难"),
    ("填空","HashMap 的默认初始容量是____",None,None,None,None,"16","HashMap 默认容量 16",2,"中等"),
    ("填空","HashMap 的默认负载因子是____",None,None,None,None,"0.75","默认 loadFactor=0.75",2,"中等"),
    ("填空","ArrayList 的底层实现是____",None,None,None,None,"数组","ArrayList 基于数组",2,"中等"),
    ("填空","LinkedList 的底层实现是____",None,None,None,None,"双向链表","LinkedList 是双向链表",2,"中等"),
    ("填空","线程安全的 Map 实现类是____",None,None,None,None,"ConcurrentHashMap","CHM 并发安全",2,"中等"),
    ("填空","Java 中启动线程的方法名是____",None,None,None,None,"start","start 启动新线程",2,"中等"),
    ("填空","线程同步关键字是____",None,None,None,None,"synchronized","synchronized 实现同步",2,"中等"),
    ("填空","保证可见性的关键字是____",None,None,None,None,"volatile","volatile 保证可见性",2,"中等"),
    ("填空","JVM 中线程私有的内存区域包括虚拟机栈、本地方法栈和____",None,None,None,None,"程序计数器","PC 寄存器线程私有",2,"困难"),
    ("填空","JDK 8 替代永久代的内存区域是____",None,None,None,None,"元空间","Metaspace",2,"困难"),
    ("填空","Java 中获取类对象的方法是 obj.____()",None,None,None,None,"getClass","Object.getClass() 返回 Class",2,"中等"),
    ("填空","Java 中表示无返回值的关键字是____",None,None,None,None,"void","void 表示无返回值",2,"简单"),
    ("填空","Java 8 引入的 Lambda 表达式适用于____接口",None,None,None,None,"函数式","Lambda 适用于函数式接口",2,"中等"),
    ("填空","Java Stream 的中间操作 filter/map 等是____的",None,None,None,None,"惰性","Stream 惰性求值",2,"困难"),
    ("填空","Java 中 break 跳出循环,____跳过当前一次迭代",None,None,None,None,"continue","continue 跳过本次",2,"简单"),
    # ============ 简答题 20 道 ============
    ("简答","简述 JDK、JRE、JVM 的区别和联系",None,None,None,None,"1)JVM 是 Java 虚拟机,负责执行字节码;2)JRE=JVM+核心类库,Java 程序运行所需的环境;3)JDK=JRE+开发工具(javac、jar、jdb 等),开发 Java 程序所需。包含关系:JDK ⊇ JRE ⊇ JVM。","三者关系是高频题",5,"中等"),
    ("简答","简述 Java 面向对象的三大特性",None,None,None,None,"1)封装:把数据和操作封装在类中,通过访问修饰符控制可见性,提高安全性和复用性;2)继承:子类继承父类的属性和方法,并可以重写,实现代码复用和扩展;3)多态:同一行为有不同实现,通过父类引用指向子类对象,实现运行时绑定。","OOP 三大特性",5,"中等"),
    ("简答","简述方法重载和方法重写的区别",None,None,None,None,"重载(Overload):1)同一类中;2)方法名相同,参数列表不同(类型/个数/顺序);3)与返回值无关;4)编译时多态。重写(Override):1)子类与父类之间;2)方法签名(名+参)完全相同;3)返回类型可协变(子类型);4)访问修饰符不能更严格;5)运行时多态。","重载 vs 重写",5,"中等"),
    ("简答","简述抽象类和接口的区别",None,None,None,None,"1)关键字:abstract class vs interface;2)继承:类只能单继承抽象类,可以多实现接口;3)成员:抽象类可有普通方法和字段,接口默认 public abstract(Java8+ 可有 default/static);4)字段:接口字段默认 public static final;5)构造器:抽象类可有,接口不能;6)用途:抽象类表示 is-a,接口表示 has-a/can-do。","abstract vs interface",5,"困难"),
    ("简答","简述 String、StringBuilder 和 StringBuffer 的区别",None,None,None,None,"1)String:不可变(final char[]),修改会创建新对象,大量拼接性能差;2)StringBuilder:可变,非线程安全,单线程性能最优;3)StringBuffer:可变,线程安全(synchronized 修饰),性能稍差。选用建议:1)少量拼接用 +/String;2)单线程大量拼接用 StringBuilder;3)多线程拼接用 StringBuffer。","三者对比",5,"中等"),
    ("简答","简述 == 和 equals 的区别",None,None,None,None,"1)==:基本类型比较值,引用类型比较地址(内存中是否同一对象);2)equals:Object 默认实现是 ==,但通常被重写为比较内容(如 String.equals 比较字符序列);3)使用建议:基本类型用 ==,对象用 equals 比较内容。注意 NPE:obj.equals 可能 NPE,Objects.equals 安全。","== vs equals",5,"中等"),
    ("简答","简述 Java 集合框架的体系结构",None,None,None,None,"Java 集合分两大体系:1)Collection(单列):①List(有序可重复)→ArrayList、LinkedList、Vector;②Set(无序不重复)→HashSet、TreeSet、LinkedHashSet;③Queue(队列)→ArrayDeque、LinkedList。2)Map(双列):HashMap、TreeMap、LinkedHashMap、ConcurrentHashMap、Hashtable。Iterator 用于遍历集合。","集合体系",5,"中等"),
    ("简答","简述 ArrayList 和 LinkedList 的区别",None,None,None,None,"1)底层结构:ArrayList=动态数组,LinkedList=双向链表;2)随机访问:ArrayList O(1),LinkedList O(n);3)插入删除:中间位置 ArrayList O(n)需移动元素,LinkedList O(1)只需改指针;4)内存:ArrayList 紧凑,LinkedList 每节点额外存指针;5)使用:多读取用 ArrayList,频繁中部插入用 LinkedList。","ArrayList vs LinkedList",5,"中等"),
    ("简答","简述 HashMap 的实现原理",None,None,None,None,"1)JDK 7:数组+链表,通过 hash(key)%length 定位桶,冲突时链表;2)JDK 8 优化:数组+链表+红黑树,链表长度>8 转红黑树,降低查询时间到 O(logn);3)默认容量 16,负载因子 0.75,达到阈值扩容(2 倍);4)非线程安全,并发用 ConcurrentHashMap;5)允许 null 键值(各 1)。","HashMap 实现",5,"困难"),
    ("简答","简述 HashMap 和 ConcurrentHashMap 的区别",None,None,None,None,"1)线程安全:HashMap 不安全,CHM 安全;2)实现:HashMap=数组+链表+红黑树,CHM=同结构+CAS+synchronized(JDK7 是 Segment 分段锁);3)性能:CHM 在并发下性能更好;4)null 键值:HashMap 允许 null,CHM 不允许;5)使用场景:单线程用 HashMap,多线程用 CHM。","HashMap vs CHM",5,"困难"),
    ("简答","简述 Java 异常体系",None,None,None,None,"Java 异常体系顶层是 Throwable,分两大类:1)Error:严重错误,如 OutOfMemoryError、StackOverflowError,程序无法处理;2)Exception:可处理异常,分两类:①受检异常(checked):IOException、SQLException 等,必须捕获或抛出;②运行时异常(unchecked,RuntimeException):NPE、ArrayIndexOutOfBounds 等,无需显式声明。","异常体系",5,"中等"),
    ("简答","简述创建线程的几种方式及优缺点",None,None,None,None,"1)继承 Thread:简单,但 Java 单继承,资源共享不方便;2)实现 Runnable:推荐,可避免单继承限制,易共享资源,但无返回值无异常;3)实现 Callable:有返回值,可抛异常,配合 FutureTask 使用;4)线程池(Executors/ThreadPoolExecutor):推荐生产使用,可复用、控制并发数。","创建线程方式",5,"中等"),
    ("简答","简述 synchronized 和 Lock 的区别",None,None,None,None,"1)实现:synchronized 是 JVM 关键字,Lock 是 JUC 接口;2)释放:synchronized 自动释放(异常/方法结束),Lock 必须 finally 显式 unlock;3)中断:synchronized 不可中断,Lock.lockInterruptibly 可中断;4)公平性:synchronized 非公平,Lock 可指定公平/非公平;5)条件:Lock 可有多个 Condition,synchronized 只有一个等待队列。","sync vs Lock",5,"困难"),
    ("简答","简述 volatile 关键字的作用",None,None,None,None,"volatile 提供两点保证:1)可见性:写入立即刷新到主内存,读取直接从主内存读,避免线程缓存导致的脏读;2)有序性:禁止指令重排序(通过内存屏障)。但注意:volatile 不保证原子性(如 i++ 不安全)。典型场景:状态标志、双重检查锁(DCL)中的 instance 字段。","volatile 三特性",5,"困难"),
    ("简答","简述 ThreadLocal 的原理和应用场景",None,None,None,None,"原理:每个 Thread 有一个 ThreadLocalMap,key 是 ThreadLocal 对象,value 是数据。每个线程独立访问自己的副本,实现线程隔离。应用:1)用户上下文(UserContext);2)数据库连接;3)事务管理;4)SimpleDateFormat 线程安全使用。注意:必须 remove() 防止内存泄漏(尤其在线程池中)。","ThreadLocal 高频题",5,"困难"),
    ("简答","简述 JVM 内存结构",None,None,None,None,"JVM 五大内存区域:1)程序计数器(PC):线程私有,记录当前字节码地址;2)虚拟机栈:线程私有,存方法栈帧(局部变量、操作数栈、动态链接、返回地址);3)本地方法栈:线程私有,native 方法用;4)堆:线程共享,对象实例,GC 主要区域;5)方法区(JDK 8+ 元空间):线程共享,类元数据、常量池、静态变量。","JVM 内存",5,"困难"),
    ("简答","简述 GC 算法",None,None,None,None,"1)标记-清除:标记后清除,缺点是产生碎片;2)复制算法:把存活对象复制到另一区域,无碎片但浪费空间,新生代用;3)标记-整理:标记后将存活对象向一端移动,无碎片不浪费,老年代用;4)分代收集:基于'对象朝生夕灭'假说,新生代用复制,老年代用标记-整理。GC 收集器:Serial、Parallel、CMS、G1、ZGC 等。","GC 算法",5,"困难"),
    ("简答","简述 JVM 类加载过程",None,None,None,None,"类加载 7 阶段:1)加载(Loading):查找并读取 .class 文件到内存,生成 Class 对象;2)验证(Verification):校验字节码格式合法;3)准备(Preparation):为静态变量分配内存,赋默认值;4)解析(Resolution):符号引用转直接引用;5)初始化(Initialization):执行 <clinit>,真正赋值;6)使用;7)卸载。其中验证、准备、解析合称连接。","类加载过程",5,"困难"),
    ("简答","简述双亲委派模型及其作用",None,None,None,None,"双亲委派:类加载请求先委派给父类加载器,父类无法加载才由自己加载。三层结构:Bootstrap(根)→Extension(扩展)→Application(应用)。作用:1)避免类重复加载;2)防止核心类被篡改(如自定义 java.lang.String 不会生效);3)保证类的唯一性。打破双亲委派的场景:JDBC 驱动、JNDI、Tomcat WebappClassLoader。","双亲委派",5,"困难"),
    ("简答","简述 Java 8 的主要新特性",None,None,None,None,"1)Lambda 表达式:简化函数式接口实例化;2)Stream API:集合的函数式操作(filter/map/reduce);3)接口默认方法和静态方法:接口可有方法体;4)Optional:防 NPE;5)新日期时间 API(java.time):替换 Date/Calendar;6)函数式接口(Function/Predicate/Consumer/Supplier);7)方法引用 Class::method;8)Nashorn JS 引擎(JDK 11 移除)。","Java 8 新特性",5,"中等"),
]
