"""
AI Introduction v2.5 - subject increment

Target: baseline 90 -> 300 (delta 210)
Type breakdown: single 80 / multi 40 / judge 40 / fill 30 / essay 20

Knowledge points:
  AI 历史/搜索/知识表示/机器学习/深度学习/NLP/CV/强化学习/伦理
"""

INCREMENTAL = [
    # ============ 单选题 80 道 ============
    # --- AI 历史与基础 ---
    ("单选","人工智能(AI)的概念最早提出于","1956 年达特茅斯会议","1950 年图灵测试","1980 年专家系统","2012 年深度学习","A","1956 达特茅斯会议",2,"中等"),
    ("单选","图灵测试由谁提出","图灵","麦卡锡","明斯基","纽厄尔","A","1950 年 Alan Turing 提出",2,"中等"),
    ("单选","下列哪个是图灵测试的判断标准","机器能否欺骗人类","机器能否计算","机器能否记忆","机器能否搜索","A","图灵测试看交互模仿能力",2,"中等"),
    ("单选","下列哪个不是 AI 三大学派","符号主义","连接主义","行为主义","结构主义","D","AI 三大学派",2,"困难"),
    ("单选","符号主义的核心是","逻辑推理","神经网络","进化","感知","A","符号主义=逻辑",2,"中等"),
    ("单选","连接主义的核心是","神经网络","逻辑","规则","知识","A","连接主义=神经网络",2,"中等"),
    ("单选","行为主义的核心是","感知-行动","逻辑","规则","知识","A","行为主义=感知行动",2,"困难"),
    ("单选","下列哪个是 AI 的弱定义","完成特定任务的智能","通用智能","拟人智能","数学智能","A","Weak AI = 特定任务",2,"中等"),
    ("单选","AGI 表示","通用人工智能","专用人工智能","弱人工智能","数据人工智能","A","AGI: Artificial General Intelligence",2,"中等"),
    # --- 搜索 ---
    ("单选","下列哪种搜索是无信息搜索","BFS","A*","贪心","IDA*","A","BFS 无启发",2,"中等"),
    ("单选","下列哪种搜索是有信息搜索(启发式)","A*","BFS","DFS","UCS","A","A* 有启发",2,"中等"),
    ("单选","A* 算法保证最优解的条件是","启发函数可采纳","启发函数单调","f=g+h","以上都对","A","A* 可采纳保证最优",2,"困难"),
    ("单选","A* 中 f(n) 等于","g(n)+h(n)","g(n)","h(n)","g(n)*h(n)","A","f=g+h",2,"中等"),
    ("单选","下列哪个是博弈搜索算法","Minimax","BFS","DFS","UCS","A","博弈树搜索",2,"中等"),
    ("单选","Alpha-Beta 剪枝是对哪种算法的优化","Minimax","A*","BFS","UCS","A","α-β 剪枝优化博弈",2,"困难"),
    # --- 知识表示 ---
    ("单选","下列哪种是知识表示方法","谓词逻辑","产生式规则","语义网络","以上都是","D","常见知识表示",2,"中等"),
    ("单选","专家系统的核心是","知识库 + 推理引擎","数据库","UI","算法","A","ES 核心",2,"中等"),
    ("单选","下列哪个是经典专家系统","MYCIN","AlphaGo","ResNet","BERT","A","MYCIN 医疗专家系统",2,"中等"),
    ("单选","下列哪个是确定性推理","正向推理","模糊推理","概率推理","贝叶斯网络","A","正向推理是确定性",2,"困难"),
    ("单选","下列哪个是不确定性推理","贝叶斯网络","谓词逻辑","归结推理","正向推理","A","贝叶斯网络处理不确定",2,"困难"),
    # --- 机器学习 ---
    ("单选","下列哪个不是机器学习类型","监督学习","无监督学习","半监督学习","暴力学习","D","ML 三大类",2,"中等"),
    ("单选","监督学习需要","有标签数据","无标签数据","奖励信号","环境","A","监督学习有标签",2,"中等"),
    ("单选","无监督学习的目标是","发现数据结构","预测标签","最大化奖励","识别图像","A","无监督发现模式",2,"中等"),
    ("单选","下列哪个是有监督学习算法","线性回归","K-Means","PCA","DBSCAN","A","线性回归=回归(监督)",2,"中等"),
    ("单选","下列哪个是无监督学习算法","K-Means","KNN","SVM","逻辑回归","A","K-Means 聚类",2,"中等"),
    ("单选","下列哪个是分类算法","逻辑回归","线性回归","K-Means","PCA","A","逻辑回归分类",2,"中等"),
    ("单选","下列哪个是回归算法","线性回归","K-Means","KNN","SVM","A","线性回归是回归",2,"中等"),
    ("单选","KNN 算法中 K 是","近邻数","聚类数","特征数","样本数","A","K = 近邻个数",2,"中等"),
    ("单选","SVM 全称是","支持向量机","随机向量机","系统向量机","稀疏向量机","A","Support Vector Machine",2,"中等"),
    ("单选","SVM 的核心思想是","最大间隔","最小距离","最大概率","最大熵","A","SVM 求最大间隔超平面",2,"困难"),
    ("单选","下列哪个是决策树算法","ID3","KNN","SVM","K-Means","A","ID3 决策树",2,"中等"),
    ("单选","ID3 划分属性的标准是","信息增益","信息增益率","基尼系数","熵","A","ID3 用信息增益",2,"困难"),
    ("单选","C4.5 划分属性的标准是","信息增益率","信息增益","基尼系数","熵","A","C4.5 用信息增益率",2,"困难"),
    ("单选","CART 划分属性的标准是","基尼系数","信息增益","信息增益率","熵","A","CART 用基尼系数",2,"困难"),
    ("单选","下列哪个是集成学习算法","Random Forest","KNN","K-Means","PCA","A","随机森林集成",2,"中等"),
    ("单选","下列哪个是 Boosting 算法","AdaBoost","Bagging","Random Forest","KNN","A","AdaBoost",2,"困难"),
    ("单选","下列哪个是 Bagging 算法","Random Forest","AdaBoost","XGBoost","GBDT","A","Random Forest 是 Bagging",2,"困难"),
    ("单选","下列哪个不是评估分类器的指标","准确率","精确率","召回率","均方误差","D","MSE 是回归指标",2,"困难"),
    ("单选","F1 分数是","精确率和召回率的调和平均","算术平均","几何平均","加权平均","A","F1=2PR/(P+R)",2,"困难"),
    ("单选","ROC 曲线下方面积称为","AUC","F1","Precision","Recall","A","AUC: Area Under Curve",2,"困难"),
    # --- 深度学习 ---
    ("单选","下列哪个是深度学习框架","TensorFlow","Spring","Vue","React","A","TensorFlow DL 框架",2,"中等"),
    ("单选","下列哪个不是深度学习框架","PyTorch","TensorFlow","Keras","MySQL","D","MySQL 是数据库",2,"中等"),
    ("单选","下列哪个不是激活函数","Sigmoid","ReLU","Tanh","Adam","D","Adam 是优化器",2,"困难"),
    ("单选","下列哪个不是优化器","SGD","Adam","RMSprop","ReLU","D","ReLU 是激活函数",2,"困难"),
    ("单选","下列哪种激活函数最常用","ReLU","Sigmoid","Tanh","Linear","A","ReLU 主流",2,"中等"),
    ("单选","Sigmoid 函数的输出范围是","(0,1)","(-1,1)","(0,∞)","(-∞,∞)","A","Sigmoid 范围 0~1",2,"中等"),
    ("单选","Tanh 函数的输出范围是","(0,1)","(-1,1)","(0,∞)","(-∞,∞)","B","Tanh 范围 -1~1",2,"中等"),
    ("单选","Softmax 函数用于","多分类输出","二分类","回归","聚类","A","Softmax 多分类",2,"中等"),
    ("单选","下列哪个是 CNN","卷积神经网络","循环神经网络","全连接网络","注意力网络","A","CNN: Convolutional Neural Network",2,"中等"),
    ("单选","下列哪个是 RNN","循环神经网络","卷积","全连接","注意力","A","RNN: Recurrent Neural Network",2,"中等"),
    ("单选","下列哪个是 RNN 变体","LSTM","CNN","ResNet","BERT","A","LSTM 是 RNN",2,"中等"),
    ("单选","LSTM 解决的主要问题是","梯度消失","过拟合","数据不足","计算慢","A","LSTM 解决梯度消失",2,"困难"),
    ("单选","CNN 中卷积层的作用是","特征提取","分类","降维","归一化","A","卷积提取特征",2,"中等"),
    ("单选","CNN 中池化层的作用是","降维","特征提取","分类","归一化","A","池化降维",2,"中等"),
    ("单选","下列哪个不是 CNN 经典模型","ResNet","VGG","AlexNet","BERT","D","BERT 是 NLP 模型",2,"困难"),
    ("单选","ResNet 的核心创新是","残差连接","卷积","池化","激活","A","ResNet 残差结构",2,"困难"),
    ("单选","下列哪个是 NLP 预训练模型","BERT","ResNet","VGG","AlexNet","A","BERT NLP",2,"中等"),
    ("单选","下列哪个不是 NLP 预训练模型","BERT","GPT","T5","ResNet","D","ResNet CV",2,"中等"),
    ("单选","Transformer 的核心机制是","自注意力","卷积","循环","池化","A","Self-Attention",2,"困难"),
    ("单选","BERT 全称是","Bidirectional Encoder Representations from Transformers","Basic Encoder Recurrent Transformer","以上都不","Bidirectional ELMo Recurrent Transformer","A","BERT 双向 Transformer 编码器",2,"困难"),
    ("单选","GPT 全称是","Generative Pre-trained Transformer","Generic Pre-trained Transformer","Generative Predictive Transformer","以上都不","A","Generative Pre-trained",2,"困难"),
    ("单选","下列哪个 LLM 由 OpenAI 开发","GPT-4","BERT","T5","ERNIE","A","GPT 系列 OpenAI",2,"中等"),
    ("单选","下列哪个不是大语言模型","GPT","LLaMA","BERT","ResNet","D","ResNet 是 CV",2,"中等"),
    # --- 训练 ---
    ("单选","下列哪个是损失函数","MSE","ReLU","Sigmoid","Adam","A","MSE 损失函数",2,"中等"),
    ("单选","下列哪个用于多分类的损失函数","交叉熵","MSE","MAE","Hinge","A","交叉熵分类",2,"中等"),
    ("单选","梯度下降法的核心是","沿梯度反方向更新参数","沿梯度方向","随机更新","固定更新","A","GD 反梯度方向",2,"中等"),
    ("单选","下列哪个不是梯度下降变种","BGD","SGD","Mini-batch GD","ABGD","D","三种主要变种",2,"困难"),
    ("单选","下列哪种正则化最常用","L1 / L2","Dropout","BatchNorm","以上都对","D","常见正则化",2,"中等"),
    ("单选","Dropout 的作用是","防止过拟合","加速训练","提升表达","降低损失","A","Dropout 防过拟合",2,"困难"),
    ("单选","BatchNorm 的作用是","加速训练 + 稳定","防止过拟合","降低损失","压缩模型","A","BN 加速稳定",2,"困难"),
    # --- 强化学习 ---
    ("单选","强化学习的核心是","奖励驱动","标签驱动","聚类驱动","回归驱动","A","RL 奖励驱动",2,"中等"),
    ("单选","下列哪个是强化学习算法","Q-Learning","K-Means","PCA","KNN","A","Q-Learning RL",2,"中等"),
    ("单选","下列哪个是著名 RL 应用","AlphaGo","BERT","GPT","ResNet","A","AlphaGo RL+DL",2,"中等"),
    ("单选","RL 中的 Agent 是","执行动作的主体","环境","奖励","状态","A","Agent 决策主体",2,"中等"),
    ("单选","RL 中的 Reward 是","环境对动作的反馈","策略","状态","目标","A","Reward 环境反馈",2,"中等"),
    # --- 应用 ---
    ("单选","下列哪个是计算机视觉任务","图像分类","机器翻译","对话生成","语音识别","A","CV 任务",2,"简单"),
    ("单选","下列哪个是自然语言处理任务","机器翻译","图像分类","目标检测","图像分割","A","NLP 任务",2,"简单"),
    ("单选","下列哪个不是 AI 应用","自动驾驶","人脸识别","语音助手","操作系统","D","OS 不是 AI",2,"中等"),
    ("单选","下列哪个是 AI 伦理问题","算法歧视","隐私泄露","就业冲击","以上都是","D","AI 伦理多方面",2,"中等"),
    ("单选","ChatGPT 基于什么模型","GPT","BERT","ResNet","VGG","A","ChatGPT 基于 GPT",2,"简单"),
    ("单选","Stable Diffusion 是什么类型的模型","图像生成","图像分类","语音识别","机器翻译","A","Stable Diffusion 文生图",2,"中等"),
    # ============ 多选题 40 道 ============
    ("多选","AI 三大学派","符号主义","连接主义","行为主义","结构主义","A,B,C","AI 三大学派",3,"中等"),
    ("多选","下列属于机器学习类型","监督学习","无监督学习","半监督学习","强化学习","A,B,C,D","ML 四大类",3,"中等"),
    ("多选","下列属于监督学习算法","线性回归","逻辑回归","SVM","决策树","A,B,C,D","监督学习",3,"中等"),
    ("多选","下列属于无监督学习算法","K-Means","DBSCAN","PCA","Apriori","A,B,C,D","无监督学习",3,"中等"),
    ("多选","下列属于分类算法","逻辑回归","SVM","决策树","KNN","A,B,C,D","分类算法",3,"中等"),
    ("多选","下列属于回归算法","线性回归","岭回归","LASSO","SVR","A,B,C,D","回归算法",3,"中等"),
    ("多选","下列属于聚类算法","K-Means","DBSCAN","层次聚类","谱聚类","A,B,C,D","聚类算法",3,"中等"),
    ("多选","下列属于集成学习方法","Bagging","Boosting","Stacking","投票","A,B,C,D","集成方法",3,"困难"),
    ("多选","下列属于 Boosting 算法","AdaBoost","GBDT","XGBoost","LightGBM","A,B,C,D","Boosting 家族",3,"困难"),
    ("多选","下列属于决策树算法","ID3","C4.5","CART","Random Forest","A,B,C,D","决策树家族",3,"中等"),
    ("多选","下列属于评估分类的指标","准确率","精确率","召回率","F1 分数","A,B,C,D","分类评估",3,"中等"),
    ("多选","下列属于评估回归的指标","MSE","RMSE","MAE","R²","A,B,C,D","回归评估",3,"困难"),
    ("多选","下列属于深度学习框架","TensorFlow","PyTorch","Keras","MXNet","A,B,C,D","DL 框架",3,"中等"),
    ("多选","下列属于激活函数","Sigmoid","Tanh","ReLU","Softmax","A,B,C,D","常见激活",3,"中等"),
    ("多选","下列属于优化器","SGD","Adam","RMSprop","Adagrad","A,B,C,D","常见优化器",3,"中等"),
    ("多选","下列属于 CNN 经典模型","LeNet","AlexNet","VGG","ResNet","A,B,C,D","CNN 经典",3,"中等"),
    ("多选","下列属于 RNN 变体","LSTM","GRU","BiRNN","Seq2Seq","A,B,C,D","RNN 变体",3,"困难"),
    ("多选","下列属于 NLP 预训练模型","BERT","GPT","T5","XLNet","A,B,C,D","NLP 预训练",3,"中等"),
    ("多选","下列属于大语言模型","GPT","LLaMA","Claude","通义千问","A,B,C,D","LLM 代表",3,"中等"),
    ("多选","下列属于损失函数","MSE","MAE","Cross-Entropy","Hinge","A,B,C,D","常见损失",3,"困难"),
    ("多选","下列属于正则化方法","L1","L2","Dropout","BatchNorm","A,B,C,D","正则化",3,"中等"),
    ("多选","下列属于过拟合的解决方法","正则化","Dropout","数据增强","早停","A,B,C,D","防过拟合",3,"困难"),
    ("多选","下列属于强化学习算法","Q-Learning","SARSA","DQN","Policy Gradient","A,B,C,D","RL 算法",3,"困难"),
    ("多选","RL 的核心要素包括","Agent","Environment","Reward","State","A,B,C,D","RL 五要素",3,"中等"),
    ("多选","下列属于 CV 任务","图像分类","目标检测","图像分割","人脸识别","A,B,C,D","CV 任务",3,"中等"),
    ("多选","下列属于 NLP 任务","机器翻译","文本分类","命名实体识别","对话生成","A,B,C,D","NLP 任务",3,"中等"),
    ("多选","下列属于知识表示方法","谓词逻辑","产生式规则","语义网络","本体","A,B,C,D","KR 方法",3,"困难"),
    ("多选","下列属于经典专家系统","MYCIN","DENDRAL","XCON","CLIPS","A,B,C,D","专家系统",3,"困难"),
    ("多选","下列属于搜索算法","BFS","DFS","A*","UCS","A,B,C,D","搜索算法",3,"中等"),
    ("多选","下列属于启发式搜索","A*","贪心","IDA*","Best-First","A,B,C,D","启发式搜索",3,"困难"),
    ("多选","下列属于 AI 应用领域","自动驾驶","人脸识别","语音助手","推荐系统","A,B,C,D","AI 应用",3,"中等"),
    ("多选","下列属于 AI 伦理问题","算法歧视","隐私泄露","就业冲击","责任归属","A,B,C,D","AI 伦理",3,"中等"),
    ("多选","下列属于生成式 AI","ChatGPT","Stable Diffusion","DALL-E","Midjourney","A,B,C,D","生成式 AI",3,"中等"),
    ("多选","下列属于 AI 训练硬件","GPU","TPU","FPGA","NPU","A,B,C,D","AI 硬件",3,"中等"),
    ("多选","下列属于数据预处理方法","归一化","标准化","缺失值填充","特征工程","A,B,C,D","数据预处理",3,"中等"),
    ("多选","下列属于特征工程方法","特征选择","特征提取","特征构造","特征编码","A,B,C,D","特征工程",3,"困难"),
    ("多选","下列属于神经网络训练步骤","前向传播","损失计算","反向传播","参数更新","A,B,C,D","训练步骤",3,"中等"),
    ("多选","下列属于 GAN 组成","生成器","判别器","损失","优化器","A,B","GAN 双网络",3,"困难"),
    ("多选","下列属于自编码器类型","原始 AE","降噪 AE","稀疏 AE","变分 AE","A,B,C,D","AE 家族",3,"困难"),
    ("多选","下列属于贝叶斯方法","朴素贝叶斯","贝叶斯网络","HMM","贝叶斯优化","A,B,C,D","贝叶斯家族",3,"困难"),
    # ============ 判断题 40 道 ============
    ("判断","图灵测试由阿兰·图灵提出",None,None,None,None,"正确","1950 年提出",1,"中等"),
    ("判断","人工智能的概念在 1956 年达特茅斯会议提出",None,None,None,None,"正确","Dartmouth Conference",1,"中等"),
    ("判断","符号主义以神经网络为核心",None,None,None,None,"错误","符号主义=逻辑",1,"困难"),
    ("判断","连接主义以神经网络为核心",None,None,None,None,"正确","连接主义=NN",1,"中等"),
    ("判断","BFS 是有信息搜索",None,None,None,None,"错误","BFS 无启发",1,"中等"),
    ("判断","A* 算法是有信息搜索",None,None,None,None,"正确","A* 用启发函数",1,"中等"),
    ("判断","A* 启发函数可采纳保证最优",None,None,None,None,"正确","可采纳保证最优",1,"困难"),
    ("判断","Minimax 是博弈搜索",None,None,None,None,"正确","Minimax 博弈树",1,"中等"),
    ("判断","Alpha-Beta 是 Minimax 的剪枝优化",None,None,None,None,"正确","α-β 剪枝",1,"困难"),
    ("判断","专家系统由知识库和推理引擎组成",None,None,None,None,"正确","ES 核心",1,"中等"),
    ("判断","机器学习需要大量数据",None,None,None,None,"正确","ML 数据驱动",1,"简单"),
    ("判断","监督学习需要标签数据",None,None,None,None,"正确","监督=有标签",1,"中等"),
    ("判断","K-Means 是监督学习算法",None,None,None,None,"错误","K-Means 是无监督",1,"中等"),
    ("判断","SVM 是分类和回归算法",None,None,None,None,"正确","SVM/SVR",1,"中等"),
    ("判断","ID3 用基尼系数划分",None,None,None,None,"错误","ID3 用信息增益",1,"困难"),
    ("判断","Random Forest 是 Bagging",None,None,None,None,"正确","RF 是 Bagging",1,"困难"),
    ("判断","XGBoost 是 Boosting",None,None,None,None,"正确","XGBoost Boosting",1,"困难"),
    ("判断","F1 是精确率和召回率的调和平均",None,None,None,None,"正确","F1 调和平均",1,"困难"),
    ("判断","深度学习是机器学习的子集",None,None,None,None,"正确","DL ⊂ ML",1,"中等"),
    ("判断","ReLU 是最常用的激活函数",None,None,None,None,"正确","ReLU 主流",1,"中等"),
    ("判断","Sigmoid 输出范围 0~1",None,None,None,None,"正确","Sigmoid 范围",1,"中等"),
    ("判断","Softmax 用于多分类输出层",None,None,None,None,"正确","Softmax 多分类",1,"中等"),
    ("判断","CNN 适合图像处理",None,None,None,None,"正确","CNN 主要用于 CV",1,"简单"),
    ("判断","RNN 适合处理序列数据",None,None,None,None,"正确","RNN 序列模型",1,"中等"),
    ("判断","LSTM 解决了 RNN 梯度消失问题",None,None,None,None,"正确","LSTM 改进 RNN",1,"困难"),
    ("判断","ResNet 用残差连接解决深度网络退化",None,None,None,None,"正确","ResNet 残差",1,"困难"),
    ("判断","BERT 是 Transformer 的编码器结构",None,None,None,None,"正确","BERT=Encoder",1,"困难"),
    ("判断","GPT 是 Transformer 的解码器结构",None,None,None,None,"正确","GPT=Decoder",1,"困难"),
    ("判断","ChatGPT 由 OpenAI 开发",None,None,None,None,"正确","OpenAI 出品",1,"简单"),
    ("判断","Dropout 用于防止过拟合",None,None,None,None,"正确","Dropout 防过拟合",1,"中等"),
    ("判断","BatchNorm 加速训练并提升稳定性",None,None,None,None,"正确","BN 作用",1,"困难"),
    ("判断","梯度下降沿梯度方向更新",None,None,None,None,"错误","沿反方向",1,"中等"),
    ("判断","SGD 是随机梯度下降",None,None,None,None,"正确","SGD: Stochastic GD",1,"中等"),
    ("判断","Adam 是优化器",None,None,None,None,"正确","Adam 是常用优化器",1,"中等"),
    ("判断","强化学习靠奖励信号驱动",None,None,None,None,"正确","RL 奖励驱动",1,"中等"),
    ("判断","AlphaGo 战胜了围棋世界冠军",None,None,None,None,"正确","2016 击败李世石",1,"简单"),
    ("判断","GPU 比 CPU 更适合深度学习训练",None,None,None,None,"正确","GPU 并行计算",1,"中等"),
    ("判断","Stable Diffusion 是图像分类模型",None,None,None,None,"错误","Stable Diffusion 是文生图",1,"中等"),
    ("判断","AI 伦理涉及隐私、公平和责任",None,None,None,None,"正确","AI 伦理多维度",1,"中等"),
    ("判断","AGI 是通用人工智能",None,None,None,None,"正确","Artificial General Intelligence",1,"中等"),
    # ============ 填空题 30 道 ============
    ("填空","人工智能的概念在____年达特茅斯会议提出",None,None,None,None,"1956","Dartmouth 1956",2,"中等"),
    ("填空","图灵测试由____提出",None,None,None,None,"图灵","Alan Turing 1950",2,"中等"),
    ("填空","AI 三大学派:符号主义、连接主义和____",None,None,None,None,"行为主义","三大学派",2,"中等"),
    ("填空","A* 算法的评估函数是 f(n) = g(n) + ____",None,None,None,None,"h(n)","f=g+h",2,"中等"),
    ("填空","机器学习类型主要分为监督学习、无监督学习和____",None,None,None,None,"强化学习","ML 三大类",2,"中等"),
    ("填空","SVM 全称是____",None,None,None,None,"Support Vector Machine","支持向量机",2,"中等"),
    ("填空","SVM 的核心思想是寻找____间隔的超平面",None,None,None,None,"最大","SVM 最大间隔",2,"困难"),
    ("填空","ID3 算法用____作为划分标准",None,None,None,None,"信息增益","ID3 信息增益",2,"困难"),
    ("填空","CART 算法用____作为划分标准",None,None,None,None,"基尼系数","CART 基尼",2,"困难"),
    ("填空","K-Means 是____学习算法",None,None,None,None,"无监督","聚类无监督",2,"中等"),
    ("填空","F1 = 2 × P × R / (____)",None,None,None,None,"P+R","F1 调和平均",2,"困难"),
    ("填空","ROC 曲线下面积称为____",None,None,None,None,"AUC","Area Under Curve",2,"困难"),
    ("填空","CNN 全称是____",None,None,None,None,"Convolutional Neural Network","卷积神经网络",2,"中等"),
    ("填空","RNN 全称是____",None,None,None,None,"Recurrent Neural Network","循环神经网络",2,"中等"),
    ("填空","LSTM 全称是____",None,None,None,None,"Long Short-Term Memory","长短期记忆",2,"困难"),
    ("填空","GAN 全称是____",None,None,None,None,"Generative Adversarial Network","生成对抗网络",2,"困难"),
    ("填空","BERT 全称是____",None,None,None,None,"Bidirectional Encoder Representations from Transformers","BERT 全称",2,"困难"),
    ("填空","GPT 全称是____",None,None,None,None,"Generative Pre-trained Transformer","GPT 全称",2,"困难"),
    ("填空","Transformer 的核心机制是____",None,None,None,None,"自注意力","Self-Attention",2,"困难"),
    ("填空","ChatGPT 由____公司开发",None,None,None,None,"OpenAI","OpenAI",2,"简单"),
    ("填空","ReLU 全称是____",None,None,None,None,"Rectified Linear Unit","线性整流",2,"中等"),
    ("填空","Sigmoid 函数输出范围是____",None,None,None,None,"(0,1)","Sigmoid 0~1",2,"中等"),
    ("填空","Softmax 函数用于____分类输出层",None,None,None,None,"多","Softmax 多分类",2,"中等"),
    ("填空","深度学习的常用优化器有 SGD 和____",None,None,None,None,"Adam","SGD/Adam",2,"中等"),
    ("填空","防止过拟合的技术有 L1/L2 正则化、Dropout 和____",None,None,None,None,"早停","早停 Early Stopping",2,"困难"),
    ("填空","强化学习的三大要素:Agent、Environment 和____",None,None,None,None,"Reward","RL 三要素",2,"中等"),
    ("填空","Q-Learning 是一种____学习算法",None,None,None,None,"强化","Q-Learning RL",2,"中等"),
    ("填空","AlphaGo 击败了围棋世界冠军____",None,None,None,None,"李世石","2016 击败李世石",2,"简单"),
    ("填空","AGI 全称是____",None,None,None,None,"Artificial General Intelligence","通用人工智能",2,"中等"),
    ("填空","训练深度学习的常用硬件是 GPU 和____",None,None,None,None,"TPU","GPU/TPU",2,"中等"),
    # ============ 简答题 20 道 ============
    ("简答","简述人工智能的定义",None,None,None,None,"AI(Artificial Intelligence)是研究、开发用于模拟、延伸和扩展人智能的理论、方法、技术及应用系统的学科。AI 让机器具备认知能力,如学习、推理、感知、规划、决策、语言理解等。AI 分为弱 AI(完成特定任务)和强 AI/AGI(通用智能,接近人类水平)。AI 是计算机科学的一个分支,与机器学习、深度学习关系密切:DL ⊂ ML ⊂ AI。","AI 定义",5,"中等"),
    ("简答","简述图灵测试",None,None,None,None,"图灵测试由 Alan Turing 在 1950 年论文 'Computing Machinery and Intelligence' 中提出。测试方式:让人类裁判与机器和另一个人通过文本对话,若裁判不能可靠区分对方是人还是机器,则机器通过测试,可认为具有智能。意义:1)首次给智能下了可操作的判断标准;2)开启了 AI 哲学的讨论;3)避免直接定义'思考'的难题。批评:只关注语言模仿,忽视感知/运动等智能形式。","图灵测试",5,"中等"),
    ("简答","简述 AI 三大学派",None,None,None,None,"AI 三大学派:1)符号主义(Symbolism):基于物理符号系统假设,通过逻辑推理和符号操作实现智能,代表:专家系统、谓词逻辑、定理证明。2)连接主义(Connectionism):模拟人脑神经网络,通过大量神经元的连接和权重实现智能,代表:神经网络、深度学习。3)行为主义(Behaviorism):基于感知-行动循环,通过与环境交互实现智能,代表:进化算法、机器人学、强化学习。三派各有侧重,现代 AI 倾向融合。","AI 三大学派",5,"中等"),
    ("简答","简述机器学习的三大类型",None,None,None,None,"1)监督学习(Supervised):有标签数据,学习输入到输出的映射,典型任务:分类(逻辑回归、SVM、决策树)、回归(线性回归);2)无监督学习(Unsupervised):无标签,发现数据结构,典型任务:聚类(K-Means、DBSCAN)、降维(PCA、t-SNE)、关联规则(Apriori);3)强化学习(Reinforcement):通过试错和奖励学习最优策略,典型算法:Q-Learning、DQN、Policy Gradient。半监督学习介于监督和无监督之间。","ML 类型",5,"中等"),
    ("简答","简述监督学习的工作流程",None,None,None,None,"监督学习流程:1)数据收集:获取有标签数据集;2)数据预处理:清洗、缺失值填充、归一化、特征工程;3)划分数据:训练集/验证集/测试集(常 8:1:1);4)选择模型:根据任务选(分类:逻辑回归/SVM/树;回归:线性/树/NN);5)训练模型:用训练集学习参数,用损失函数衡量误差;6)调参:用验证集调超参;7)评估:用测试集评估指标(准确率、F1、AUC、MSE);8)部署:上线服务。","监督学习流程",5,"中等"),
    ("简答","简述决策树算法及其划分标准",None,None,None,None,"决策树通过递归地把样本按特征划分到子集,构造一棵树进行分类/回归。三种经典算法:1)ID3:用信息增益(熵)选最优属性,但偏向多值属性;2)C4.5:用信息增益率,克服 ID3 偏置,支持连续属性;3)CART:用基尼系数(分类)或方差(回归),生成二叉树。优点:可解释性强、不需归一化、能处理混合类型。缺点:易过拟合(用剪枝/集成解决)。","决策树",5,"困难"),
    ("简答","简述集成学习的三大方法",None,None,None,None,"集成学习通过组合多个弱学习器获得更强模型:1)Bagging(并行):并行训练多个模型(在 Bootstrap 采样的子集上),最后投票/平均。代表:Random Forest。优点:降低方差。2)Boosting(串行):按顺序训练模型,后模型关注前模型的错误。代表:AdaBoost、GBDT、XGBoost、LightGBM。优点:降低偏差。3)Stacking:用多个不同模型的输出作为新特征,训练元模型。常在比赛中获胜方案。","集成学习",5,"困难"),
    ("简答","简述深度学习与传统机器学习的区别",None,None,None,None,"1)特征工程:传统 ML 需手工特征;DL 端到端自动学习特征;2)数据需求:DL 需大量数据(百万级);ML 数据少也能用;3)硬件:DL 需 GPU/TPU;ML CPU 即可;4)可解释性:ML(树/线性)强;DL 弱(黑箱);5)适用任务:DL 在 CV/NLP/语音上突破;ML 在结构化数据(表格)仍有优势;6)训练时间:DL 长;ML 短;7)调参:DL 复杂(网络结构、学习率等);ML 简单。","DL vs ML",5,"中等"),
    ("简答","简述 CNN 的核心思想和典型结构",None,None,None,None,"CNN(卷积神经网络)针对图像设计:1)核心思想:①局部感受野(Local Receptive Field):每个神经元只看局部;②权值共享(Weight Sharing):同一卷积核在不同位置共享参数,大幅减少参数;③池化(Pooling):降维并提供平移不变性。2)典型结构:输入→[卷积+ReLU+池化]×N→展平→全连接→Softmax 输出。3)经典模型:LeNet、AlexNet、VGG、GoogLeNet、ResNet(残差连接解决深度退化)。","CNN",5,"困难"),
    ("简答","简述 RNN 及其变体",None,None,None,None,"RNN(循环神经网络)处理序列数据,神经元有循环连接,记忆历史:h_t = f(W·x_t + U·h_{t-1})。问题:长序列梯度消失/爆炸。变体:1)LSTM(长短期记忆):用三个门(输入门、遗忘门、输出门)和细胞状态,有效缓解梯度消失,擅长长序列;2)GRU(门控循环单元):简化的 LSTM,只有更新门和重置门,参数少;3)BiRNN:双向 RNN,同时考虑前后文;4)Seq2Seq:编码器-解码器结构,用于机器翻译。现在被 Transformer 部分取代。","RNN 变体",5,"困难"),
    ("简答","简述 Transformer 架构",None,None,None,None,"Transformer 由 Vaswani 等于 2017 年提出 ('Attention is All You Need'),完全基于注意力机制。1)核心机制:自注意力(Self-Attention),Q/K/V 矩阵实现序列内任意位置的关联;2)结构:Encoder-Decoder,各 6 层。每层:多头注意力 + Add&Norm + 前馈网络 + Add&Norm;3)位置编码:用三角函数注入位置信息;4)优势:并行计算、长距离依赖;5)衍生:BERT(只用 Encoder)、GPT(只用 Decoder)、T5(Encoder-Decoder)。改变了 NLP 乃至 CV/语音格局。","Transformer",5,"困难"),
    ("简答","简述 BERT 与 GPT 的区别",None,None,None,None,"1)架构:BERT 用 Transformer Encoder(双向);GPT 用 Decoder(单向自回归)。2)预训练任务:BERT 用 MLM(Masked Language Model)+ NSP;GPT 用自回归语言模型(预测下一词)。3)适用任务:BERT 适合理解任务(分类、问答、NER);GPT 适合生成任务(对话、写作)。4)规模:BERT 参数较小(110M-340M);GPT 系列从 117M 到 GPT-4 数千亿参数。5)使用方式:BERT fine-tune;GPT 大模型用 prompt。","BERT vs GPT",5,"困难"),
    ("简答","简述深度学习的反向传播算法",None,None,None,None,"反向传播(Backpropagation, BP)是训练神经网络的核心算法。流程:1)前向传播:输入经过各层得到输出和损失;2)计算损失对输出的梯度;3)反向传播:从输出层逐层向输入层应用链式法则,计算每层参数对损失的梯度;4)参数更新:用梯度下降更新参数 w ← w - η·∂L/∂w。优势:利用计算图共享中间结果,效率高 O(网络规模)。框架(TensorFlow/PyTorch)用自动微分实现。","反向传播",5,"困难"),
    ("简答","简述梯度下降及其变种",None,None,None,None,"梯度下降:沿负梯度方向更新参数,θ ← θ - η·∇L(θ)。变种:1)BGD(批量):用全部数据计算梯度,精确但慢;2)SGD(随机):每次一个样本,快但震荡;3)Mini-batch GD:折中,常用,batch_size=32~256;4)动量法(Momentum):累积历史梯度方向,加速收敛;5)Adagrad:每个参数自适应学习率;6)RMSprop:Adagrad 改进,指数移动平均;7)Adam:综合动量和 RMSprop,最常用,默认 lr=0.001。","梯度下降",5,"困难"),
    ("简答","简述过拟合及其解决方法",None,None,None,None,"过拟合:模型在训练集表现好,在测试集表现差,记住了噪声而非规律。原因:模型复杂、数据少。解决方法:1)增加数据:数据增强(图像翻转/裁剪)、合成数据;2)正则化:L1(稀疏)、L2(权重衰减);3)Dropout:训练时随机失活神经元;4)Early Stopping:验证集 loss 不再下降时停止;5)简化模型:减少层数/神经元;6)集成学习:多模型平均;7)BatchNorm:稳定训练;8)交叉验证:充分利用数据。","过拟合",5,"困难"),
    ("简答","简述强化学习",None,None,None,None,"强化学习(RL)让 Agent 在环境中通过试错学习最优策略以最大化累积奖励。五要素:Agent、Environment、State、Action、Reward。马尔可夫决策过程(MDP)是其数学框架。算法分类:1)Value-based:Q-Learning、DQN(深度 Q 网络);2)Policy-based:Policy Gradient、REINFORCE;3)Actor-Critic:A2C、A3C、PPO 等。应用:AlphaGo(围棋)、Atari 游戏、机器人、自动驾驶、ChatGPT 的 RLHF。","强化学习",5,"困难"),
    ("简答","简述生成式 AI",None,None,None,None,"生成式 AI 通过学习训练数据分布,生成类似的新数据。1)文本生成:GPT 系列(ChatGPT)、LLaMA、Claude;2)图像生成:Stable Diffusion、DALL-E、Midjourney;3)语音生成:VITS、Tacotron;4)视频生成:Sora、Runway;5)代码生成:Copilot、Cursor。底层技术:Transformer(LLM)、扩散模型(图像)、GAN。生成式 AI 是 AI 的重要新方向,带来产业变革,也引发伦理(深度伪造、版权等)讨论。","生成式 AI",5,"中等"),
    ("简答","简述 NLP 的主要任务",None,None,None,None,"NLP(自然语言处理)主要任务:1)分词/词性标注;2)命名实体识别(NER):识别人名、地名、组织;3)文本分类:情感分析、垃圾邮件检测;4)机器翻译:中英互译;5)问答系统:阅读理解、知识问答;6)文本摘要:抽取式/生成式;7)对话系统:聊天机器人、智能助手;8)语言模型:预测下一词,LLM 基础;9)文本生成:写作、续写。当前主流方法:基于 Transformer 的预训练大模型 + Fine-tune 或 Prompt。","NLP 任务",5,"中等"),
    ("简答","简述 CV 的主要任务",None,None,None,None,"CV(计算机视觉)主要任务:1)图像分类:识别图像类别;2)目标检测:定位+分类(YOLO、R-CNN);3)图像分割:像素级分类(语义分割、实例分割,U-Net、Mask R-CNN);4)人脸识别:身份验证;5)关键点检测:姿态估计;6)图像生成:GAN、Stable Diffusion;7)图像描述:Image Captioning;8)OCR:文字识别;9)视频分析:动作识别、视频理解;10)自动驾驶感知:车道线、目标、深度。主流模型:CNN(ResNet)、Vision Transformer(ViT)。","CV 任务",5,"中等"),
    ("简答","简述 AI 伦理问题",None,None,None,None,"AI 伦理涉及多方面问题:1)算法歧视/公平性:训练数据偏见导致歧视(性别、种族);2)隐私泄露:大模型可能记忆并泄露训练数据;3)可解释性:深度学习黑箱难以解释决策;4)责任归属:自动驾驶事故责任谁负;5)就业冲击:替代部分白领工作;6)虚假信息:深度伪造、AI 生成假新闻;7)军事化:AI 武器自主决策;8)版权:训练数据使用、生成内容归属。需要多方共治:技术、法律、伦理、监管协同。","AI 伦理",5,"中等"),
]
