"""
College English v2.5 - subject increment

Target: baseline 90 -> 300 (delta 210)
Type breakdown: single 80 / multi 40 / judge 40 / fill 30 / essay 20

Knowledge points:
  词汇/语法/时态/语态/从句/词组/CET-4 常考点/写作/翻译
"""

INCREMENTAL = [
    # ============ 单选题 80 道 ============
    # --- 时态 ---
    ("单选","I ___ TV when my mother came in.","watched","was watching","watch","am watching","B","过去进行时:was/were + V-ing",2,"中等"),
    ("单选","She ___ to Beijing twice.","has been","has gone","went","goes","A","has been to 去过(已回);has gone to 去了(未回)",2,"中等"),
    ("单选","By next year, I ___ here for ten years.","will work","will be working","will have worked","work","C","将来完成时 will have V-ed",2,"困难"),
    ("单选","If I ___ you, I would accept the offer.","am","were","be","was","B","虚拟语气过去时用 were",2,"困难"),
    ("单选","He said he ___ to the cinema.","goes","went","had gone","has gone","C","主句过去时,从句过去完成",2,"中等"),
    ("单选","The bus ___ at 8 every morning.","leave","leaves","is leaving","left","B","一般现在时第三人称单数",2,"简单"),
    ("单选","She ___ her homework already.","finished","has finished","is finishing","finishes","B","already 用现在完成时",2,"中等"),
    ("单选","Look! It ___ outside.","rains","rained","is raining","has rained","C","Look! 用现在进行",2,"简单"),
    ("单选","I ___ him for ten years.","know","knew","have known","am knowing","C","for + 时段用现在完成",2,"中等"),
    ("单选","When I got home, my mother ___ dinner.","cooked","was cooking","has cooked","is cooking","B","when + 过去时,主句过去进行",2,"中等"),
    # --- 语态 ---
    ("单选","English ___ all over the world.","speaks","is speaking","is spoken","spoke","C","被动语态 is spoken",2,"中等"),
    ("单选","The book ___ by him last year.","wrote","was written","is written","writes","B","过去被动 was/were V-ed",2,"中等"),
    ("单选","Many trees ___ every year.","plant","are planted","planted","plants","B","主语 trees 是被种,被动",2,"中等"),
    ("单选","The window ___ broken yesterday.","is","was","has been","be","B","yesterday 用过去式",2,"中等"),
    ("单选","The bridge ___ now.","is building","is being built","builds","is built","B","正在被建,现在进行被动",2,"困难"),
    # --- 从句 ---
    ("单选","The man ___ is talking to her is my brother.","who","whom","which","whose","A","定语从句先行词指人作主语",2,"中等"),
    ("单选","I don't know ___ he will come.","that","whether","which","what","B","whether 是否",2,"中等"),
    ("单选","I'll go ___ you go.","wherever","whatever","whoever","whichever","A","wherever 无论哪里",2,"中等"),
    ("单选","___ he is busy, he still helps me.","Although","Because","If","As","A","Although 尽管(让步)",2,"中等"),
    ("单选","I won't go ___ you go with me.","unless","if","when","because","A","unless 除非",2,"中等"),
    ("单选","This is the place ___ I was born.","which","that","where","when","C","where 表示地点",2,"中等"),
    ("单选","Do you remember the day ___ we first met?","which","that","where","when","D","when 表示时间",2,"中等"),
    ("单选","The reason ___ he was late is unknown.","why","because","that","which","A","why 表原因",2,"困难"),
    ("单选","___ is known to all, the earth is round.","It","As","Which","That","B","As is known to all 众所周知",2,"困难"),
    # --- 非谓语 ---
    ("单选","I enjoy ___ music.","listening to","listen to","to listen to","listened to","A","enjoy + V-ing",2,"中等"),
    ("单选","He decided ___ abroad.","go","to go","going","went","B","decide + to V",2,"中等"),
    ("单选","The book is worth ___.","read","reading","to read","to be read","B","be worth + V-ing",2,"中等"),
    ("单选","I'd rather ___ at home than go out.","stay","to stay","staying","stayed","A","would rather + V",2,"困难"),
    ("单选","___ in 1900, the building has a long history.","Built","Building","Build","To build","A","过去分词作状语,建筑被建",2,"困难"),
    ("单选","She left without ___ goodbye.","saying","to say","said","say","A","without + V-ing",2,"中等"),
    # --- 比较级 ---
    ("单选","She is ___ than her sister.","tall","taller","tallest","more taller","B","tall 单音节 -er",2,"简单"),
    ("单选","This book is ___ interesting than that one.","more","most","much","very","A","more interesting 比较级",2,"中等"),
    ("单选","He runs the ___ in our class.","fast","faster","fastest","most fast","C","the fastest 最高级",2,"中等"),
    ("单选","The harder you work, ___.","you'll succeed more","the more you'll succeed","more you'll succeed","you will more succeed","B","the more...the more 越...越...",2,"困难"),
    # --- 介词 ---
    ("单选","I'm interested ___ English.","in","at","on","for","A","be interested in",2,"简单"),
    ("单选","He is good ___ math.","in","at","on","for","B","be good at",2,"简单"),
    ("单选","I'll meet you ___ Monday.","at","in","on","by","C","on + 星期",2,"简单"),
    ("单选","She was born ___ 1990.","at","in","on","by","B","in + 年份",2,"简单"),
    ("单选","Let's meet ___ 8 o'clock.","at","in","on","by","A","at + 时刻",2,"简单"),
    ("单选","He looks ___ his father.","like","as","such","at","A","look like 看起来像",2,"中等"),
    # --- 词组 ---
    ("单选","I look forward ___ from you.","to hear","to hearing","hear","hearing","B","look forward to + V-ing",2,"困难"),
    ("单选","She got used ___ early.","to get up","to getting up","get up","getting up","B","be used to + V-ing",2,"困难"),
    ("单选","I prefer tea ___ coffee.","than","to","from","of","B","prefer A to B",2,"困难"),
    ("单选","He devoted himself ___ his work.","to","at","in","on","A","devote oneself to",2,"困难"),
    ("单选","She is in charge ___ this project.","of","with","for","at","A","in charge of 负责",2,"中等"),
    ("单选","I have to put up ___ the noise.","with","up","off","on","A","put up with 忍受",2,"困难"),
    ("单选","Take ___ your coat, it's hot.","off","on","up","out","A","take off 脱下",2,"简单"),
    ("单选","Don't give ___ no matter what happens.","up","in","off","out","A","give up 放弃",2,"简单"),
    ("单选","He looks ___ to his teacher.","up","forward","down","at","A","look up to 尊敬",2,"中等"),
    ("单选","The plane took ___ on time.","off","on","up","over","A","take off (飞机)起飞",2,"中等"),
    # --- 冠词 ---
    ("单选","She is ___ honest girl.","a","an","the","/","B","honest h 不发音用 an",2,"中等"),
    ("单选","I have ___ apple.","a","an","the","/","B","apple 元音开头用 an",2,"简单"),
    ("单选","___ sun rises in ___ east.","A; an","The; the","A; the","The; an","B","太阳/方位用 the",2,"中等"),
    ("单选","He plays ___ piano well.","a","an","the","/","C","play the + 乐器",2,"中等"),
    ("单选","He plays ___ basketball every day.","a","an","the","/","D","play + 球类不加冠词",2,"中等"),
    # --- 词汇 ---
    ("单选","I cannot ___ his attitude.","stand","stop","start","store","A","cannot stand 受不了",2,"中等"),
    ("单选","Please ___ me a favor.","do","make","give","take","A","do sb a favor 帮个忙",2,"中等"),
    ("单选","The teacher ___ us a story.","said","told","spoke","talked","B","tell sb a story",2,"中等"),
    ("单选","She ___ English very well.","says","tells","speaks","talks","C","speak + 语言",2,"中等"),
    ("单选","They ___ about the news.","said","told","spoke","talked","D","talk about 谈论",2,"中等"),
    ("单选","The medicine ___ a bitter taste.","has","is","have","are","A","has 第三人称单数",2,"简单"),
    ("单选","The news ___ true.","is","are","were","be","A","news 不可数,is",2,"中等"),
    ("单选","Either you or he ___ wrong.","am","is","are","be","B","就近原则 he is",2,"困难"),
    ("单选","Neither of them ___ here.","am","is","are","be","B","neither + of + 复数,单数动词",2,"困难"),
    # --- 习语 ---
    ("单选","It rains cats and ___.","dogs","cats","rats","horses","A","rain cats and dogs 倾盆大雨",2,"中等"),
    ("单选","Break a ___ ! (好运)","arm","leg","head","foot","B","break a leg 祝好运",2,"困难"),
    ("单选","Once in a ___ moon.","red","blue","green","yellow","B","once in a blue moon 极少",2,"困难"),
    ("单选","Piece of ___ (容易).","bread","cake","pie","candy","B","piece of cake 小菜一碟",2,"中等"),
    ("单选","The ball is in your ___ now.","hand","court","field","ground","B","ball in your court 看你的了",2,"困难"),
    # --- 阅读 ---
    ("单选","'Procrastinate' means ___.","delay","hurry","arrive","start","A","procrastinate 拖延",2,"困难"),
    ("单选","'Ubiquitous' means ___.","rare","common","unique","strange","B","ubiquitous 无处不在",2,"困难"),
    ("单选","'Inevitable' means ___.","unavoidable","possible","difficult","easy","A","inevitable 不可避免的",2,"困难"),
    ("单选","'Diligent' means ___.","lazy","careless","hardworking","quick","C","diligent 勤奋的",2,"中等"),
    ("单选","'Ambiguous' means ___.","clear","unclear","beautiful","ugly","B","ambiguous 模糊的",2,"困难"),
    ("单选","'Persuade' means ___.","convince","refuse","accept","reject","A","persuade 说服",2,"中等"),
    ("单选","'Indispensable' means ___.","unnecessary","important","useful","rare","B","indispensable 不可或缺",2,"困难"),
    ("单选","'Optimistic' means ___.","pessimistic","positive","negative","neutral","B","optimistic 乐观",2,"中等"),
    ("单选","'Conservative' means ___.","liberal","traditional","modern","progressive","B","conservative 保守的",2,"困难"),
    ("单选","'Versatile' means ___.","limited","multi-skilled","narrow","simple","B","versatile 多才多艺",2,"困难"),
    ("单选","CET-4 中 'curriculum' 意思是","课程","俱乐部","习惯","流行","A","curriculum 课程",2,"困难"),
    # ============ 多选题 40 道 ============
    ("多选","下列哪些是英语基本时态","一般现在","一般过去","一般将来","现在完成","A,B,C,D","常见时态",3,"中等"),
    ("多选","英语句子基本成分包括","主语","谓语","宾语","状语","A,B,C,D","句子成分",3,"中等"),
    ("多选","下列哪些是英语句子类型","简单句","并列句","复合句","疑问句","A,B,C","三大句型",3,"中等"),
    ("多选","英语三大从句包括","名词性从句","定语从句","状语从句","系动词从句","A,B,C","三大从句",3,"困难"),
    ("多选","名词性从句包括","主语从句","宾语从句","表语从句","同位语从句","A,B,C,D","四类名词性",3,"困难"),
    ("多选","状语从句类型包括","时间","地点","原因","结果","A,B,C,D","状语从句类",3,"困难"),
    ("多选","下列哪些是 to 后接 V-ing 的短语","look forward to","be used to","object to","devote to","A,B,C,D","to + V-ing",3,"困难"),
    ("多选","下列接 V-ing 的动词","enjoy","finish","mind","practice","A,B,C,D","接动名词",3,"中等"),
    ("多选","下列接 to V 的动词","decide","plan","hope","want","A,B,C,D","接不定式",3,"中等"),
    ("多选","下列既接 V-ing 又接 to V 的动词","like","love","start","begin","A,B,C,D","两种均可",3,"困难"),
    ("多选","下列哪些是不可数名词","water","information","news","advice","A,B,C,D","不可数名词",3,"中等"),
    ("多选","下列哪些是可数名词","apple","book","desk","chair","A,B,C,D","可数名词",3,"中等"),
    ("多选","下列哪些是形容词比较级前用的副词","much","far","a little","still","A,B,C,D","修饰比较级",3,"困难"),
    ("多选","下列哪些是关系代词","who","whom","whose","which","A,B,C,D","关系代词",3,"困难"),
    ("多选","下列哪些是关系副词","when","where","why","how","A,B,C","when/where/why",3,"困难"),
    ("多选","下列哪些是不及物动词","arrive","happen","occur","exist","A,B,C,D","不及物常见",3,"困难"),
    ("多选","下列哪些是英语助动词","be","have","do","will","A,B,C,D","助动词",3,"中等"),
    ("多选","下列哪些是英语情态动词","can","may","must","should","A,B,C,D","情态动词",3,"中等"),
    ("多选","下列哪些是常见 used to 用法","be used to + V-ing","used to do","be used to do(被用来)","get used to + V-ing","A,B,C,D","used to 三种",3,"困难"),
    ("多选","下列哪些表达虚拟语气","If I were you","I wish I had","It's time you did","If only","A,B,C,D","虚拟语气标志",3,"困难"),
    ("多选","下列哪些是英语写作常用连接词","however","therefore","moreover","besides","A,B,C,D","连接词",3,"中等"),
    ("多选","下列哪些是英语写作转折词","however","but","yet","while","A,B,C,D","转折词",3,"中等"),
    ("多选","下列哪些是英语写作因果词","because","since","as","for","A,B,C,D","因果词",3,"中等"),
    ("多选","下列哪些是英语写作列举词","first","second","next","finally","A,B,C,D","顺序词",3,"中等"),
    ("多选","下列哪些是英语写作举例词","for example","for instance","such as","like","A,B,C,D","举例词",3,"中等"),
    ("多选","下列哪些是英语写作总结词","in conclusion","to sum up","in short","overall","A,B,C,D","总结词",3,"中等"),
    ("多选","下列哪些是 CET-4 高频词汇","contribute","analyze","emphasize","investigate","A,B,C,D","CET-4 词汇",3,"困难"),
    ("多选","下列哪些是 CET-4 高频形容词","considerable","essential","significant","appropriate","A,B,C,D","CET-4 形容词",3,"困难"),
    ("多选","下列哪些是常见介词","in","on","at","by","A,B,C,D","常见介词",3,"中等"),
    ("多选","下列哪些是固定搭配","take care of","get rid of","look after","make use of","A,B,C,D","固定搭配",3,"中等"),
    ("多选","下列哪些动词常用被动语态","build(建造)","write(写)","speak(说)","grow(种植)","A,B,C,D","被动常用",3,"中等"),
    ("多选","下列哪些是 there be 句型","There is","There are","There was","There were","A,B,C,D","there be",3,"中等"),
    ("多选","下列哪些是 it 的用法","it 形式主语","it 形式宾语","it 强调句","it 指时间天气","A,B,C,D","it 多种用法",3,"困难"),
    ("多选","下列哪些是英语写作 letter 类型","application letter","invitation letter","complaint letter","thank-you letter","A,B,C,D","信件类型",3,"中等"),
    ("多选","下列哪些是常见动词短语 get","get up","get over","get along","get rid of","A,B,C,D","get 短语",3,"中等"),
    ("多选","下列哪些是常见动词短语 take","take off","take care","take place","take part in","A,B,C,D","take 短语",3,"中等"),
    ("多选","下列哪些是常见动词短语 put","put on","put off","put up","put away","A,B,C,D","put 短语",3,"中等"),
    ("多选","下列哪些是常见动词短语 make","make up","make out","make sense","make use of","A,B,C,D","make 短语",3,"中等"),
    ("多选","下列哪些是常见副词后缀","-ly","-wise","-ward","-ways","A,B,C,D","副词后缀",3,"困难"),
    ("多选","下列哪些是常见形容词后缀","-able","-ful","-less","-ive","A,B,C,D","形容词后缀",3,"困难"),
    # ============ 判断题 40 道 ============
    ("判断","一般现在时第三人称单数动词加 -s",None,None,None,None,"正确","三单加 -s/-es",1,"简单"),
    ("判断","现在完成时用 have/has + 过去分词",None,None,None,None,"正确","have V-ed",1,"中等"),
    ("判断","过去进行时用 was/were + V-ing",None,None,None,None,"正确","过去进行时",1,"中等"),
    ("判断","虚拟语气中 be 动词用 were",None,None,None,None,"正确","虚拟语气 were",1,"困难"),
    ("判断","被动语态用 be + 过去分词",None,None,None,None,"正确","被动语态结构",1,"中等"),
    ("判断","since + 时间点用现在完成时",None,None,None,None,"正确","since 现在完成",1,"中等"),
    ("判断","ago 通常用一般过去时",None,None,None,None,"正确","ago 过去时",1,"中等"),
    ("判断","look forward to 后接动词原形",None,None,None,None,"错误","后接 V-ing",1,"困难"),
    ("判断","be used to 后接动名词,used to 后接动词原形",None,None,None,None,"正确","两个用法不同",1,"困难"),
    ("判断","定语从句关系代词指人用 who",None,None,None,None,"正确","who/whom 指人",1,"中等"),
    ("判断","定语从句关系代词指物用 which",None,None,None,None,"正确","which 指物",1,"中等"),
    ("判断","that 既可指人也可指物",None,None,None,None,"正确","that 通用",1,"中等"),
    ("判断","whose 表示所属关系",None,None,None,None,"正确","whose 所属",1,"中等"),
    ("判断","Although 后可以接 but",None,None,None,None,"错误","although 不与 but 连用",1,"困难"),
    ("判断","unless = if not",None,None,None,None,"正确","unless 等于 if not",1,"中等"),
    ("判断","wish 后多接虚拟语气",None,None,None,None,"正确","wish + 虚拟",1,"困难"),
    ("判断","enjoy 后接动名词",None,None,None,None,"正确","enjoy + V-ing",1,"中等"),
    ("判断","decide 后接动名词",None,None,None,None,"错误","decide + to V",1,"中等"),
    ("判断","worth 后接动名词",None,None,None,None,"正确","be worth + V-ing",1,"中等"),
    ("判断","tell sb sth 的语序与 say to sb sth 一样",None,None,None,None,"错误","tell sb sth, say sth to sb",1,"困难"),
    ("判断","speak + 语言,如 speak English",None,None,None,None,"正确","speak + 语言",1,"中等"),
    ("判断","talk about 表示谈论",None,None,None,None,"正确","talk about sth",1,"中等"),
    ("判断","good 比较级是 gooder",None,None,None,None,"错误","good 比较级 better",1,"中等"),
    ("判断","bad 比较级是 worse",None,None,None,None,"正确","bad → worse",1,"中等"),
    ("判断","many 比较级是 more",None,None,None,None,"正确","many → more",1,"中等"),
    ("判断","数词序数词第一是 first",None,None,None,None,"正确","first",1,"简单"),
    ("判断","一周第二天是 Tuesday",None,None,None,None,"正确","周一是第一天",1,"简单"),
    ("判断","一年第二个月是 February",None,None,None,None,"正确","二月",1,"简单"),
    ("判断","news 是不可数名词",None,None,None,None,"正确","news 不可数",1,"中等"),
    ("判断","information 是不可数名词",None,None,None,None,"正确","information 不可数",1,"中等"),
    ("判断","advice 可数",None,None,None,None,"错误","advice 不可数",1,"中等"),
    ("判断","an 用于元音音素开头的词前",None,None,None,None,"正确","an + 元音",1,"中等"),
    ("判断","an honest man 是正确的",None,None,None,None,"正确","h 不发音用 an",1,"困难"),
    ("判断","I am, you are, he are 都正确",None,None,None,None,"错误","he is 不是 he are",1,"简单"),
    ("判断","Either A or B + 动词,就近原则",None,None,None,None,"正确","就近原则",1,"困难"),
    ("判断","Neither of them 后跟单数动词",None,None,None,None,"正确","neither + 单数",1,"困难"),
    ("判断","piece of cake 表示困难",None,None,None,None,"错误","piece of cake = 容易",1,"中等"),
    ("判断","rain cats and dogs 表示倾盆大雨",None,None,None,None,"正确","习语",1,"中等"),
    ("判断","CET-4 是大学英语四级考试",None,None,None,None,"正确","CET-4",1,"简单"),
    ("判断","English 是 SVO 语序",None,None,None,None,"正确","英语主谓宾",1,"中等"),
    # ============ 填空题 30 道 ============
    ("填空","I have ___ pen.",None,None,None,None,"a","a/an 用法",2,"简单"),
    ("填空","She ___ to school every day.",None,None,None,None,"goes","三单 goes",2,"简单"),
    ("填空","English is ___ all over the world.",None,None,None,None,"spoken","被动语态",2,"中等"),
    ("填空","I will ___ him tomorrow.",None,None,None,None,"meet","将来时 will",2,"中等"),
    ("填空","If I ___ rich, I would travel.",None,None,None,None,"were","虚拟语气",2,"困难"),
    ("填空","I look forward to ___ from you.",None,None,None,None,"hearing","to + V-ing",2,"困难"),
    ("填空","She is interested ___ music.",None,None,None,None,"in","be interested in",2,"中等"),
    ("填空","He is good ___ English.",None,None,None,None,"at","be good at",2,"中等"),
    ("填空","Can you do me a ___ ?",None,None,None,None,"favor","do a favor",2,"中等"),
    ("填空","'Optimistic' 的反义词是____",None,None,None,None,"pessimistic","optimistic",2,"困难"),
    ("填空","'Increase' 的反义词是____",None,None,None,None,"decrease","increase/decrease",2,"中等"),
    ("填空","'Accept' 的反义词是____",None,None,None,None,"reject","accept/reject",2,"中等"),
    ("填空","'Polite' 的反义词是____",None,None,None,None,"rude","polite/rude",2,"中等"),
    ("填空","'Begin' 的同义词是____",None,None,None,None,"start","begin/start",2,"中等"),
    ("填空","'Big' 的同义词是____",None,None,None,None,"large","big/large",2,"中等"),
    ("填空","'Famous' 的同义词是____",None,None,None,None,"well-known","famous/well-known",2,"中等"),
    ("填空","I ___ to Beijing twice.",None,None,None,None,"have been","have been to",2,"中等"),
    ("填空","I have lived here ___ 2010.",None,None,None,None,"since","since",2,"中等"),
    ("填空","The book is ___ reading.",None,None,None,None,"worth","be worth",2,"困难"),
    ("填空","She ___ a doctor when she grew up.",None,None,None,None,"wanted to be","want to be",2,"中等"),
    ("填空","'A piece of ___ ' 表示容易",None,None,None,None,"cake","piece of cake",2,"中等"),
    ("填空","'Better late than ___' (迟做总比不做好)",None,None,None,None,"never","习语",2,"中等"),
    ("填空","CET-4 全称是____",None,None,None,None,"College English Test Band 4","CET-4",2,"困难"),
    ("填空","TOEFL 全称是____",None,None,None,None,"Test of English as a Foreign Language","TOEFL",2,"困难"),
    ("填空","IELTS 全称是____",None,None,None,None,"International English Language Testing System","IELTS",2,"困难"),
    ("填空","SVO 表示主语-动词-____",None,None,None,None,"宾语","SVO 主谓宾",2,"中等"),
    ("填空","'Difficult' 的反义词是____",None,None,None,None,"easy","difficult/easy",2,"简单"),
    ("填空","'Important' 的同义词是____",None,None,None,None,"significant","important/significant",2,"中等"),
    ("填空","'Help' 的同义词是____",None,None,None,None,"assist","help/assist",2,"中等"),
    ("填空","在书面语中,'a lot of' 多用____替代",None,None,None,None,"many/much","a lot of 替换",2,"困难"),
    # ============ 简答题 20 道 ============
    ("简答","Please introduce yourself in English (about 100 words).",None,None,None,None,"My name is XXX, and I am a student at XX University, majoring in Computer Science. I was born in XXX City. I love programming, reading and playing basketball. In my spare time, I enjoy learning new things, especially in the field of AI. My goal is to become a good software engineer who can contribute to society. I work hard and never give up. I am also a friendly and outgoing person who likes making friends. Thank you for listening.","自我介绍模板",5,"简单"),
    ("简答","Please write a short essay on 'The Importance of Learning English'.",None,None,None,None,"English is one of the most important languages in the world. First, it is widely used in business and academic communication. Almost all international conferences and journals use English. Second, learning English helps us access global information and culture. Most websites, books, and movies are in English. Third, English skills are crucial for our career. Many companies require English proficiency. In conclusion, learning English broadens our horizons and creates more opportunities. We should keep working on it.","学英语重要性",5,"中等"),
    ("简答","Please describe your favorite hobby in English.",None,None,None,None,"My favorite hobby is reading. I started reading at the age of 6 when my parents gave me a children's storybook. Now I read various books, including novels, history, and technology. Reading helps me relax after a busy day and broadens my knowledge. I particularly enjoy reading at night before bed. My favorite book is 'The Three-Body Problem'. Through reading, I have learned about different cultures and ways of thinking. I plan to read at least 30 books this year.","爱好描述",5,"简单"),
    ("简答","Please write an email to your friend, inviting him to your birthday party.",None,None,None,None,"Dear John, I hope this email finds you well. I am writing to invite you to my birthday party next Saturday at 6 p.m. The party will be held at my home. We will have dinner, play games, and watch a movie together. Many of our old friends will be there too. It would be wonderful if you could join us. Please let me know if you can come. Looking forward to seeing you. Best regards, Tom","邀请信",5,"中等"),
    ("简答","Please briefly describe a memorable trip you have had.",None,None,None,None,"Last summer, I went to Beijing with my family. It was my first time visiting the capital. We visited the Great Wall, the Forbidden City, and Tiananmen Square. The Great Wall impressed me the most because of its magnificent view and rich history. We also tried Peking Duck, which was delicious. The trip lasted five days, during which we took many photos and made wonderful memories. I learned a lot about Chinese history and culture. I would love to visit Beijing again in the future.","旅行描述",5,"中等"),
    ("简答","What are the basic English tenses? Briefly explain.",None,None,None,None,"English has 16 tenses, formed by combining 4 time references (present, past, future, past future) with 4 aspects (simple, continuous, perfect, perfect continuous). The most common ones include: 1) Simple present (I work); 2) Simple past (I worked); 3) Simple future (I will work); 4) Present continuous (I am working); 5) Past continuous (I was working); 6) Present perfect (I have worked); 7) Past perfect (I had worked). Each tense expresses a specific time and aspect of action.","英语时态",5,"困难"),
    ("简答","Please explain the structure of an English sentence.",None,None,None,None,"An English sentence usually has 5 basic structures: 1) S+V (Subject + Verb): He runs. 2) S+V+O (Subject + Verb + Object): I love English. 3) S+V+P (Subject + Linking Verb + Predicative): She is happy. 4) S+V+IO+DO (Subject + Verb + Indirect Object + Direct Object): He gave me a book. 5) S+V+O+OC (Subject + Verb + Object + Object Complement): They made him happy. Sentences can be combined into compound or complex sentences using conjunctions or relative pronouns.","英语句子结构",5,"困难"),
    ("简答","Please explain the difference between active voice and passive voice.",None,None,None,None,"1) Active voice: The subject performs the action. Structure: S + V + O. Example: 'Tom wrote the letter.' Used to emphasize the doer. 2) Passive voice: The subject receives the action. Structure: S + be + V-ed (+ by + agent). Example: 'The letter was written by Tom.' Used when: a) the doer is unknown or unimportant; b) we want to emphasize the receiver; c) in scientific or formal writing. Conversion: Active object becomes passive subject, verb changes to 'be + past participle'.","主动被动",5,"困难"),
    ("简答","Please explain when to use the present perfect tense.",None,None,None,None,"Present perfect (have/has + V-ed) is used when: 1) An action started in the past and continues to now: 'I have lived here for 10 years.' 2) An action just completed with present relevance: 'I have finished my homework.' 3) Past experience without specific time: 'I have been to Paris.' 4) With time markers: already, yet, ever, never, just, recently, since, for. Compared to simple past: simple past emphasizes 'when'; present perfect emphasizes 'now'.","现在完成时",5,"困难"),
    ("简答","Please describe a useful English study method.",None,None,None,None,"Effective English study methods include: 1) Vocabulary: Learn 20 new words daily and review systematically using apps like Anki; 2) Listening: Watch English movies/TV shows with subtitles, then without. Listen to podcasts (TED, BBC); 3) Speaking: Find a language partner, use shadowing technique. Don't fear mistakes; 4) Reading: Start with simple novels, gradually increase difficulty. Read newspapers (China Daily); 5) Writing: Keep a daily diary in English, write essays on topics; 6) Grammar: Don't memorize rules - use it. Combine input (listen/read) and output (speak/write).","学习方法",5,"中等"),
    ("简答","Please briefly compare British English and American English.",None,None,None,None,"Differences between British (BrE) and American English (AmE): 1) Spelling: colour/color, centre/center, theatre/theater, organise/organize. 2) Vocabulary: lift/elevator, lorry/truck, biscuit/cookie, flat/apartment, holiday/vacation. 3) Pronunciation: BrE 'r' is silent at end of words; AmE pronounces 'r'. 4) Grammar: BrE uses present perfect more often; AmE uses simple past more. 5) Date format: BrE day/month/year; AmE month/day/year. Both are mutually intelligible. Choose one and stick to it for consistency.","英美英语",5,"中等"),
    ("简答","What is your dream job and why?",None,None,None,None,"My dream job is to be a software engineer specializing in artificial intelligence. There are several reasons. First, I love coding and have been programming since high school. The feeling of bringing ideas to life through code is amazing. Second, AI is transforming the world. From self-driving cars to ChatGPT, AI applications are everywhere, and I want to be part of this revolution. Third, this career offers good salary and growth opportunities. To achieve this dream, I am studying computer science, learning machine learning, and doing internships at tech companies.","梦想工作",5,"中等"),
    ("简答","Please describe your hometown.",None,None,None,None,"My hometown is XX, a beautiful city in eastern China. It has a population of about 10 million. The city has a long history of over 2000 years and many historical sites. The climate is mild, with four distinct seasons. Spring is full of flowers, summer is hot, autumn is cool with golden leaves, and winter is sometimes snowy. The local cuisine is famous, especially XX dishes. People are friendly and hardworking. In recent years, the city has developed rapidly with modern buildings and convenient transportation. I love my hometown and miss it very much.","家乡描述",5,"简单"),
    ("简答","Please briefly explain what 'Internet' is.",None,None,None,None,"The Internet is a global network connecting millions of computers worldwide. It allows people to communicate, share information, and access services online. Key features: 1) Global connectivity through TCP/IP protocols; 2) Offers various services: email, web browsing, social media, video streaming, online shopping; 3) Decentralized architecture - no single point of control; 4) Built on the World Wide Web (WWW), which uses HTTP/HTTPS. Major impacts include transforming education (online learning), business (e-commerce), and society (social media). The Internet has become an essential part of modern life.","互联网",5,"中等"),
    ("简答","Please write a short complaint letter about a defective product.",None,None,None,None,"Dear Sir/Madam, I am writing to complain about a smartphone I purchased from your online store on March 15. The phone arrived with a cracked screen and a malfunctioning camera. Despite following the user manual, the phone shuts down randomly. The order number is XYZ-12345. I would like to request a full refund or replacement of the defective product. I have attached photos as evidence. I expect your prompt response within 7 days. Looking forward to your reply. Sincerely, John Smith","投诉信",5,"中等"),
    ("简答","What advice would you give to a junior student about university life?",None,None,None,None,"My advice to a junior student: 1) Time management: balance studies and social life. Use a planner and prioritize tasks; 2) Active learning: don't just attend classes - participate, ask questions, study with peers; 3) Build relationships: make friends and connect with professors. Networks help you grow; 4) Try new things: join clubs, attend events, explore hobbies. University is for self-discovery; 5) Take care of health: exercise, eat well, sleep enough. Mental health matters; 6) Plan ahead: think about your career goals early; 7) Don't fear failure - it's part of learning. Good luck!","建议信",5,"中等"),
    ("简答","Please explain the importance of teamwork.",None,None,None,None,"Teamwork is essential in modern society. First, it brings together diverse skills and perspectives. Different team members contribute their strengths, leading to better solutions than individuals alone. Second, teamwork increases productivity. Tasks divided among team members can be completed faster. Third, it fosters communication and interpersonal skills, which are crucial in workplace. Fourth, teamwork creates a sense of belonging and motivation. Members support each other through challenges. However, effective teamwork requires good leadership, clear roles, and mutual respect. In conclusion, mastering teamwork is a key skill for success in any career.","团队合作",5,"中等"),
    ("简答","Please describe a person who has influenced you the most.",None,None,None,None,"The person who has influenced me the most is my father. He is a teacher who has been working in education for over 30 years. He has taught me three important things: First, the value of hard work. He always tells me 'No pain, no gain'. Second, the importance of integrity. He insists on doing the right thing even when no one is watching. Third, the love of learning. He still reads books every day at the age of 60. Whenever I face difficulties, I think of him and find strength. I am deeply grateful for his guidance and love.","重要的人",5,"中等"),
    ("简答","Please write about your view on online learning.",None,None,None,None,"Online learning has become widespread, especially after COVID-19. It has both advantages and disadvantages. Advantages: 1) Flexibility: learn anytime, anywhere; 2) Variety: access to global courses (Coursera, edX); 3) Cost-effective: cheaper than traditional courses; 4) Self-paced: students can learn at their own speed. Disadvantages: 1) Lack of face-to-face interaction; 2) Requires self-discipline; 3) Technology issues; 4) Difficulty in staying focused. In my opinion, online learning is a valuable supplement to traditional education. The best approach is to combine both online and offline methods.","在线学习",5,"中等"),
    ("简答","Please describe your future plans.",None,None,None,None,"In the next 5 years, I plan to: First, complete my undergraduate studies with excellent grades and pass CET-6. Second, do internships at top tech companies during summer vacations to gain practical experience. Third, prepare for graduate school, focusing on AI or software engineering. After graduation, I plan to work for 2-3 years in industry to apply what I learned. In the long term, I want to start my own tech company that solves real social problems. To achieve these goals, I will keep learning, building skills, and networking with talented people. Hard work and persistence are key.","未来计划",5,"中等"),
    # 缺口补充: 多选 12
    ("多选","下列哪些是英语写作建议","多读","多写","多改","多背范文","A,B,C,D","写作四多",3,"中等"),
    ("多选","下列哪些是英语阅读技巧","略读","扫读","精读","跳读","A,B,C,D","阅读技巧",3,"中等"),
    ("多选","下列哪些是英语听力技巧","抓关键词","记笔记","预测","回顾","A,B,C,D","听力技巧",3,"中等"),
    ("多选","下列哪些是英语口语技巧","跟读","模仿","开口说","录音","A,B,C,D","口语技巧",3,"中等"),
    ("多选","下列哪些是英语翻译技巧","直译","意译","增译","减译","A,B,C,D","翻译技巧",3,"困难"),
    ("多选","下列哪些是常见英语祈使句","Be careful","Don't worry","Stop","Listen","A,B,C,D","祈使句",3,"中等"),
    ("多选","下列哪些是常见英语感叹句","What a day","How beautiful","What a pity","How nice","A,B,C,D","感叹句",3,"中等"),
    ("多选","下列哪些是常见英语疑问句","Yes/No 疑问","特殊疑问","选择疑问","反意疑问","A,B,C,D","疑问句",3,"中等"),
    ("多选","下列哪些是英语数词类型","基数词","序数词","分数","小数","A,B,C,D","数词",3,"中等"),
    ("多选","下列哪些是 CET-4 题型","听力","阅读","翻译","写作","A,B,C,D","CET-4 题型",3,"困难"),
    ("多选","下列哪些是英语写作开头方式","定义","引言","数据","故事","A,B,C,D","开头方式",3,"困难"),
    ("多选","下列哪些是英语段落连接方式","时间","空间","逻辑","对比","A,B,C,D","段落连接",3,"困难"),
    # 缺口补充: 判断 8
    ("判断","CET-6 是大学英语六级",None,None,None,None,"正确","CET-6",1,"简单"),
    ("判断","TOEFL 是托福考试",None,None,None,None,"正确","TOEFL 托福",1,"简单"),
    ("判断","IELTS 是雅思考试",None,None,None,None,"正确","IELTS 雅思",1,"简单"),
    ("判断","英语形容词比较级有 -er 和 more 两种形式",None,None,None,None,"正确","比较级两种形式",1,"中等"),
    ("判断","英语 the 是定冠词",None,None,None,None,"正确","the 定冠词",1,"中等"),
    ("判断","英语 a/an 是不定冠词",None,None,None,None,"正确","a/an 不定冠词",1,"中等"),
    ("判断","英语主语+谓语+宾语是基本句型",None,None,None,None,"正确","SVO",1,"中等"),
    ("判断","英语动词三种基本形式:原形、过去式、过去分词",None,None,None,None,"正确","动词三态",1,"中等"),
    # 缺口补充: 填空 12
    ("填空","CET-6 全称是____",None,None,None,None,"College English Test Band 6","CET-6",2,"困难"),
    ("填空","英语 5 个元音字母是 a, e, i, o, ____",None,None,None,None,"u","aeiou",2,"简单"),
    ("填空","英语字母表共有____个字母",None,None,None,None,"26","26 letters",2,"简单"),
    ("填空","be 动词三种形式:am, is, ____",None,None,None,None,"are","are",2,"简单"),
    ("填空","have 动词第三人称单数是____",None,None,None,None,"has","has",2,"简单"),
    ("填空","do 动词第三人称单数是____",None,None,None,None,"does","does",2,"简单"),
    ("填空","good 比较级是____",None,None,None,None,"better","better",2,"中等"),
    ("填空","good 最高级是____",None,None,None,None,"best","best",2,"中等"),
    ("填空","bad 比较级是____",None,None,None,None,"worse","worse",2,"中等"),
    ("填空","bad 最高级是____",None,None,None,None,"worst","worst",2,"中等"),
    ("填空","child 复数是____",None,None,None,None,"children","children",2,"中等"),
    ("填空","mouse 复数是____",None,None,None,None,"mice","mice",2,"中等"),
    # 缺口补充: 简答 2
    ("简答","Please explain what you do every day.",None,None,None,None,"My typical day starts at 7 a.m. After getting up, I wash my face and have breakfast. Then I go to university by bus. I have classes from 8 to 12. After lunch, I study at the library or do experiments in the lab from 2 to 5 p.m. In the evening, I have dinner with my roommates. Then I review my lessons or do homework until 10 p.m. Before going to bed at 11, I read books or watch news. Weekends are different - I usually exercise, meet friends, or go shopping.","日常生活",5,"简单"),
    ("简答","Please write a short text about a recent book you read.",None,None,None,None,"I recently finished reading 'The Three-Body Problem' by Liu Cixin. It is a science fiction novel set in a complex universe. The book tells a story about humanity's first contact with an alien civilization. What impressed me most is the author's grand imagination of cosmic sociology and the depth of philosophical questions raised. The characters are vivid, especially Ye Wenjie whose decisions shape humanity's destiny. The book made me think deeply about science, civilization, and our place in the universe. I highly recommend it to anyone interested in deep science fiction.","读后感",5,"中等"),
]
